import { useState, useEffect, useCallback, useRef } from "react";

const FONT="'Pretendard',-apple-system,'Noto Sans KR',sans-serif";
const SB_URL="https://jzahuisvtglzzkmgjcnr.supabase.co";
const SB_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6YWh1aXN2dGdsenprbWdqY25yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ5MzE4MDgsImV4cCI6MjA5MDUwNzgwOH0.WWpeegaxxxJR6lROjBJLQDEofsRoKn9YxBgaoeqndJM";
const HD={"apikey":SB_KEY,"Authorization":"Bearer "+SB_KEY,"Content-Type":"application/json"};
async function dbLoad(k){try{const r=await fetch(SB_URL+"/rest/v1/couples?couple_key=eq."+encodeURIComponent(k)+"&select=data",{headers:HD});const d=await r.json();return d?.[0]?.data||null;}catch{return null;}}
async function dbSave(k,d){try{await fetch(SB_URL+"/rest/v1/couples",{method:"POST",headers:{...HD,"Prefer":"resolution=merge-duplicates,return=minimal"},body:JSON.stringify({couple_key:k,data:d,updated_at:new Date().toISOString()})});}catch(e){console.error(e);}}
function dlCSV(fn,hd,rows){const B="\uFEFF",esc=c=>'"'+String(c==null?"":c).replace(/"/g,'""')+'"';const csv=B+[hd.map(esc).join(","),...rows.map(r=>r.map(esc).join(","))].join("\n");const b=new Blob([csv],{type:"text/csv;charset=utf-8;"});const a=document.createElement("a");a.href=URL.createObjectURL(b);a.download=fn+".csv";a.click();}

const P={green:"#B5D580",greenDk:"#7BA23A",greenLt:"#E8F2D6",greenBg:"#F4F9EC",blue:"#6EC8E4",blueDk:"#3A8EB0",blueLt:"#D6EEF6",blueBg:"#EDF7FB",peri:"#92ADD8",periDk:"#5B7EAE",periLt:"#DDE6F2",periBg:"#EEF2F8",lav:"#B0A0CC",lavDk:"#7B6B9E",lavLt:"#E4DFF0",lavBg:"#F2F0F7",text:"#3A3A50",textSub:"#7A7A8E",textMuted:"#A8A8BC",bg:"#F6F9F2",border:"#E2EAD8"};

function Fl1({s}){return<svg viewBox="0 0 120 120" style={{position:"absolute",opacity:0.15,pointerEvents:"none",...s}} xmlns="http://www.w3.org/2000/svg"><defs><filter id="a"><feGaussianBlur stdDeviation="2.5"/></filter></defs><g filter="url(#a)">{[0,72,144,216,288].map((r,i)=><ellipse key={i} cx="60" cy="35" rx="22" ry="28" fill={i%2?P.blue:P.peri} transform={`rotate(${r} 60 60)`}/>)}<circle cx="60" cy="60" r="12" fill={P.lav}/></g></svg>;}
function Fl2({s}){return<svg viewBox="0 0 100 60" style={{position:"absolute",opacity:0.13,pointerEvents:"none",...s}} xmlns="http://www.w3.org/2000/svg"><defs><filter id="b"><feGaussianBlur stdDeviation="1.5"/></filter></defs><g filter="url(#b)"><path d="M50 55Q30 30 15 40Q0 50 20 55Z" fill={P.green}/><path d="M50 55Q70 30 85 40Q100 50 80 55Z" fill={P.greenLt}/><path d="M50 55Q40 15 50 5Q60 15 50 55Z" fill={P.greenDk}/></g></svg>;}

/* ═══ DYNAMIC CHECKLIST: "결혼 N개월 전" 역산 ═══ */
const CL_TEMPLATE=[
  {mbStart:14,mbEnd:10,label:"준비 시작",emoji:"🌱",items:[{id:"s01",text:"플래너 결정",cat:"planner"},{id:"s02",text:"웨딩홀 투어 후 결정",cat:"venue"},{id:"s03",text:"스드메 예약 (스튜디오·드레스·메이크업)",cat:"photo"},{id:"s04",text:"혼주 메이크업 예약",cat:"makeup"},{id:"s05",text:"본식 스냅/DVD 결정",cat:"photo"},{id:"s06",text:"허니문 예약",cat:"honeymoon"},{id:"s07",text:"결혼반지(예물) 준비",cat:"shopping"},{id:"s08",text:"예복(턱시도) 알아보기",cat:"shopping"}]},
  {mbStart:10,mbEnd:8,label:"드레스투어 & 혼수",emoji:"👗",items:[{id:"d01",text:"드레스투어 후 샵 결정",cat:"dress"},{id:"d02",text:"혼수품목 준비",cat:"shopping"},{id:"d03",text:"예복 가봉",cat:"shopping"},{id:"d04",text:"예물 디자인 셀렉·제작",cat:"shopping"},{id:"d05",text:"한복 셀렉/가봉",cat:"shopping"}]},
  {mbStart:8,mbEnd:6,label:"촬영 준비",emoji:"📸",items:[{id:"p01",text:"촬영가봉 (드레스 셀렉)",cat:"dress"},{id:"p02",text:"촬영 소품·컨셉 준비",cat:"photo"},{id:"p03",text:"생화부케 예약",cat:"flower"},{id:"p04",text:"신랑 예복 디자인 확정",cat:"shopping"}]},
  {mbStart:6,mbEnd:4,label:"스튜디오 촬영",emoji:"💛",items:[{id:"ph01",text:"스튜디오 웨딩 촬영",cat:"photo"},{id:"ph02",text:"헬퍼이모님 확인",cat:"photo"}]},
  {mbStart:4,mbEnd:3,label:"셀렉 & 청첩장",emoji:"🖼️",items:[{id:"sl01",text:"앨범/액자 사진 셀렉",cat:"photo"},{id:"sl02",text:"모바일 청첩장 제작·발송",cat:"etc"}]},
  {mbStart:3,mbEnd:1,label:"막바지 준비",emoji:"🏡",items:[{id:"f01",text:"신혼집 구하기",cat:"etc"},{id:"f02",text:"가전·가구 준비",cat:"shopping"},{id:"f03",text:"주례/사회/축가 섭외",cat:"ceremony"},{id:"f04",text:"접수대 섭외",cat:"ceremony"},{id:"f05",text:"폐백 여부 결정",cat:"ceremony"},{id:"f06",text:"2부 의상 준비",cat:"dress"},{id:"f07",text:"혼주 한복·정장",cat:"family"},{id:"f08",text:"하객 명단 정리",cat:"ceremony"}]},
  {mbStart:2,mbEnd:0,label:"본식 가봉 & 마무리",emoji:"✨",items:[{id:"b01",text:"본식 드레스 셀렉",cat:"dress"},{id:"b02",text:"원본사진 셀렉",cat:"photo"},{id:"b03",text:"종이 청첩장 발송",cat:"etc"},{id:"b04",text:"수정본·액자 수령",cat:"photo"},{id:"b05",text:"혼주 확인/예단",cat:"family"},{id:"b06",text:"식순·MR·식전영상 준비",cat:"ceremony"},{id:"b07",text:"부케 셀렉",cat:"flower"},{id:"b08",text:"식권·포토테이블 준비",cat:"ceremony"},{id:"b09",text:"비상키트 준비",cat:"ceremony"}]},
  {mbStart:0,mbEnd:0,label:"웨딩데이",emoji:"💍",items:[{id:"w01",text:"웨딩데이 ♥",cat:"ceremony"}]},
];

/* Calculate actual months-before with ratio scaling */
const BASE_PREP_MONTHS = 14; // 기본 준비 기간 (가장 여유로운 경우)

function getAvailableMonths(wd) {
  if (!wd) return BASE_PREP_MONTHS;
  const now = new Date(); now.setHours(0,0,0,0);
  const w = new Date(wd); w.setHours(0,0,0,0);
  const diff = (w.getFullYear() - now.getFullYear()) * 12 + (w.getMonth() - now.getMonth());
  return Math.max(diff, 0);
}

function scaledMb(originalMb, wd) {
  const avail = getAvailableMonths(wd);
  if (avail >= BASE_PREP_MONTHS) return originalMb; // 여유 충분 → 기본값
  if (originalMb === 0) return 0;
  const ratio = avail / BASE_PREP_MONTHS;
  return Math.max(Math.round(originalMb * ratio), originalMb === 0 ? 0 : 0);
}

function calcPhaseDate(mb, wd) {
  if (!wd) return null;
  const d = new Date(wd);
  d.setMonth(d.getMonth() - mb);
  return d;
}
function phaseDates(ph, wd) {
  const start = calcPhaseDate(scaledMb(ph.mbStart, wd), wd);
  const end = calcPhaseDate(scaledMb(ph.mbEnd, wd), wd);
  return { start, end };
}
function phaseStatus(ph, wd) {
  if (!wd) return "upcoming";
  const now = new Date(); now.setHours(0,0,0,0);
  const { start, end } = phaseDates(ph, wd);
  if (!start || !end) return "upcoming";
  if (now < start) return "upcoming";
  if (now > end) return "past";
  return "current";
}
function phaseLabel(ph, wd) {
  const s = scaledMb(ph.mbStart, wd);
  const e = scaledMb(ph.mbEnd, wd);
  if (s === 0 && e === 0) return "결혼 당월";
  if (e === 0) return s + "개월 전 ~ 결혼";
  if (s === e) return s + "개월 전";
  return s + "~" + e + "개월 전";
}
function phaseDeadline(ph, wd) {
  if (!wd) return "";
  const d = calcPhaseDate(scaledMb(ph.mbEnd, wd), wd);
  if (!d) return "";
  const w = ["일","월","화","수","목","금","토"];
  return d.getFullYear() + "." + (d.getMonth()+1) + "." + d.getDate() + "(" + w[d.getDay()] + ")";
}
function phaseDeadlineDate(ph, wd) { return calcPhaseDate(scaledMb(ph.mbEnd, wd), wd); }

const CAT={venue:{bg:"#FFF8E1",fg:"#D4A017",n:"웨딩홀",ic:"🏛️"},planner:{bg:P.lavLt,fg:P.lavDk,n:"플래너",ic:"📋"},dress:{bg:"#FCE4EC",fg:"#C62860",n:"드레스",ic:"👗"},makeup:{bg:"#FDF2F8",fg:"#B0408A",n:"메이크업",ic:"💄"},photo:{bg:P.greenLt,fg:P.greenDk,n:"촬영",ic:"📷"},shopping:{bg:"#FFF8E1",fg:"#C8960A",n:"혼수",ic:"🛍️"},honeymoon:{bg:P.blueLt,fg:P.blueDk,n:"신혼여행",ic:"✈️"},ceremony:{bg:P.periLt,fg:P.periDk,n:"예식",ic:"💒"},flower:{bg:"#FCE4EC",fg:"#C62850",n:"부케·꽃",ic:"💐"},family:{bg:P.greenLt,fg:"#5D6E3A",n:"혼주",ic:"👨‍👩‍👧"},etc:{bg:"#F0F0F0",fg:"#707080",n:"기타",ic:"📌"}};
const TIPS_BY_PHASE=[
  "💡 웨딩홀 견적서를 서면으로 꼭 받아오세요. 식대 단가, 보증인원, 초과 시 추가요금, 주차 가능 대수까지 꼼꼼히 확인하세요|💡 스드메는 최소 3곳 이상 비교하세요. 가격이 매년 상승 추세라 마음에 들면 빠른 계약이 유리해요|💡 예물 반지는 금값이 계속 오르고 있어서 빨리 결정할수록 유리해요. 디자인 제작에만 4~6주가 걸려요|💡 예산은 항목별 상한선을 정하고, 총액의 20%를 예비비로 꼭 남겨두세요. 숨은 비용(드레스 보증금, 식권 추가분, 폐백의상 대여)이 생각보다 많아요|💡 상견례 전에 양가와 결혼 날짜·예산·예단 규모를 미리 조율해두면 당일 분위기가 훨씬 편해요. 코스 요리 식당에서 룸을 예약하면 대화에 집중할 수 있어요|💡 웨딩홀 선택 시 교통(지하철 접근성)과 식사 퀄리티가 가장 중요해요. 멀리서 오시는 하객분들을 배려하세요",
  "💡 드레스 투어 시 사진 촬영이 안 되는 곳이 많아요. 메모장에 드레스 스타일, 가격, 느낌을 꼭 기록하세요|💡 드레스 지정(플래너 추천)이 자유 투어보다 20~40만원 저렴할 수 있어요. 플래너에게 비교 견적을 요청해보세요|💡 평일에 드레스샵을 방문하면 주말보다 더 다양한 드레스를 볼 수 있어요. 주말에는 본식 드레스가 빠져 있는 경우가 많거든요|💡 한복은 맞춤 시 최소 2~3개월, 대여는 1개월 전이면 충분해요. 소품(노리개, 가방, 신발)까지 세트로 준비하면 완성도가 올라가요|💡 예복(턱시도) 맞춤은 2~3번의 가봉이 필요해서 최소 3개월 전에 시작해야 여유로워요. 촬영 전 완성이 가장 이상적이에요",
  "💡 촬영가봉 때 드레스뿐 아니라 악세서리(귀걸이, 목걸이, 티아라, 베일)도 함께 매칭해보세요|💡 신랑 예복 맞춤은 촬영 3개월 전까지 시작해야 해요. 계절에 맞는 원단을 고르세요 — 여름엔 리넨, 겨울엔 울 소재가 좋아요|💡 촬영 컨셉과 소품은 커플이 함께 정하면 더 특별한 사진이 나와요. 원하는 스타일의 레퍼런스 사진을 10~15장 모아서 작가님과 공유하세요|💡 생화부케를 선택하면 사진은 예쁘지만 시들 수 있어요. 조화 부케는 오래 간직할 수 있다는 장점이 있으니 비교해보세요|💡 웨딩관리(피부, 등드름, 팔 라인)는 본식 2~3개월 전 시작해서 주 1~2회 집중 관리가 가장 효과적이에요",
  "💡 촬영 전날 충분히 수면하고, 얼굴 붓지 않게 야식과 짠 음식은 피하세요. 물은 적당히만 드세요|💡 촬영 당일 누드톤 속옷 & 스트랩리스 브라를 꼭 준비하세요. 검은색이나 무늬가 있는 속옷은 드레스 비침이 있어요|💡 헤어변형 선생님을 부르면 드레스마다 헤어를 바꿀 수 있어서 사진 퀄리티가 확 올라가요. 사전 예약 필수!|💡 촬영 전 거울 앞에서 포즈를 연습해두면 실제 촬영에서 훨씬 자연스러운 사진이 나와요|💡 촬영 당일 네일 관리도 챙기세요. 반지 컷이나 손 클로즈업 사진이 의외로 많이 나와요. 전날 네일샵 방문 추천!|💡 촬영 후 2~3주 뒤 사진 셀렉, 이후 3~4개월 뒤 최종 앨범을 받게 돼요. 포토테이블용 사진은 미리 요청하세요",
  "💡 앨범 셀렉은 2~3시간 걸려요. 페이지 추가 시 약 3.3만원/장이니 예산을 미리 계산해두세요|💡 모바일 청첩장은 결혼 6~8주 전, 종이 청첩장은 2달 전부터 발송하는 게 적당해요. 제작에 보통 10일 소요돼요|💡 청첩장 발송 전 오탈자를 꼭 확인하세요! 날짜, 시간, 장소, 계좌번호 등 여러 번 체크하세요|💡 웨딩 촬영 원본 파일은 반드시 클라우드+USB 이중 백업하세요. 날아가면 평생 후회해요",
  "💡 신혼집 입주 시기를 결혼식과 맞춰 계획하면 이사 스트레스가 확 줄어요. 계약 시 꼼꼼한 확인은 기본!|💡 축가는 최소 2개월 전에 미리 부탁하세요. 아무리 가까운 사이도 갑자기 부탁하면 부담스러워해요|💡 하객 명단은 최근 1년 내 연락했던 분들 기준으로 정리하면 효율적이에요. 참석 여부를 엑셀로 관리하면 식대 계산에도 도움돼요|💡 답례품은 부담스럽지 않으면서 실용적인 구성이 만족도가 높아요. 요즘은 소소한 것이 트렌드예요|💡 폐백은 요즘 생략 추세이지만 양가 부모님 의견을 꼭 먼저 확인하세요. 직접 준비 시 음식·그릇·인력도 미리 챙겨야 해요",
  "💡 본식 가봉은 플래너 동행이 중요해요! 그날 바로 결정해야 하니 신중하게 고르세요|💡 식순표는 사회자와 미리 공유하고, MR 음원은 USB로 준비하세요. 블루투스 연결은 불안정할 수 있어요|💡 포토테이블 사진은 어린 시절 → 학창시절 → 연애시절 → 웨딩 순으로 다양하게 준비하면 좋아요|💡 본식 전에는 새로운 피부 시술을 피하세요. 컨디션 유지에 집중하고, 자극 줄이는 게 중요해요|💡 결혼식 당일 비상키트를 미리 챙겨두세요: 바늘+실, 양면테이프, 밴드, 진통제, 여분 스타킹, 미니 재봉키트, 물티슈|💡 축의금 담당은 신뢰할 수 있는 경험자에게 맡기세요. 하객이 많으면 손바닥이 쓸리니 장갑도 준비!",
  "💍 결혼 전날 서로에게 편지를 써서 당일 아침에 교환해보세요. 소중한 추억이 됩니다|💍 당일은 예상치 못한 소소한 해프닝이 있을 수 있어요. 너무 완벽을 추구하기보다 그 순간을 즐기세요|💍 결혼식이 끝나면 장인어른·장모님께 꼭 직접 전화드리세요. 감사 인사 한 통이 큰 의미가 돼요|💍 두 분이 함께 준비해온 과정 자체가 가장 큰 선물이에요. 행복한 결혼생활의 시작을 축하합니다 ♥"
];

function fresh(){return{groomName:"",brideName:"",weddingDate:"",weddingTime:"12:00",checklist:JSON.parse(JSON.stringify(CL_TEMPLATE)).map(p=>({...p,items:p.items.map(i=>({...i,done:false,memo:""}))})),budget:[],contacts:[],keyDates:[],sdmVendors:[],sdmPhotos:[]};}

/* Migrate old data: ensure checklist phases have mbStart/mbEnd */
function migrateData(d){if(!d||!d.checklist)return d;const cl=d.checklist;let needsMigration=cl.some(p=>p.mbStart===undefined);if(!needsMigration)return d;
  // Map old checklist done/memo states onto new template
  const itemStates={};cl.forEach(p=>{(p.items||[]).forEach(i=>{itemStates[i.id]={done:i.done,memo:i.memo||""};});});
  const customItems={};cl.forEach((p,pi)=>{(p.items||[]).forEach(i=>{if(i.custom){if(!customItems[pi])customItems[pi]=[];customItems[pi].push(i);}});});
  const newCL=JSON.parse(JSON.stringify(CL_TEMPLATE)).map((p,pi)=>({...p,items:[...p.items.map(i=>({...i,done:itemStates[i.id]?.done||false,memo:itemStates[i.id]?.memo||""})),...(customItems[pi]||[])]}));
  return{...d,checklist:newCL};}

function getDday(d){if(!d)return null;const t=new Date();t.setHours(0,0,0,0);const w=new Date(d);w.setHours(0,0,0,0);return Math.ceil((w-t)/864e5);}
function fmtDate(d){if(!d)return"";const o=new Date(d),w=["일","월","화","수","목","금","토"];return o.getFullYear()+"."+(o.getMonth()+1)+"."+o.getDate()+"("+w[o.getDay()]+")";}
function fmtW(n){return n.toLocaleString("ko-KR")+"원";}
function cTips(cl,wd){const idx=cl.findIndex(p=>phaseStatus(p,wd)==="current");const i=idx>=0?idx:cl.findIndex(p=>phaseStatus(p,wd)==="upcoming");if(i<0)return["🎉 모든 준비 완료!"];const all=(TIPS_BY_PHASE[i]||"💡 차근차근 준비해보세요").split("|");if(all.length<=3)return all;const shuffled=[...all].sort(()=>Math.random()-0.5);return shuffled.slice(0,3);}
function Bg({cat,cn}){const c=CAT[cat];if(c)return<span style={{padding:"4px 10px",borderRadius:8,fontSize:11,fontWeight:600,background:c.bg,color:c.fg,whiteSpace:"nowrap"}}>{c.ic} {c.n}</span>;return<span style={{padding:"4px 10px",borderRadius:8,fontSize:11,fontWeight:600,background:P.blueLt,color:P.blueDk,whiteSpace:"nowrap"}}>✏️ {cn||"기타"}</span>;}

function Modal({title,open,onClose,children}){if(!open)return null;return<div style={{position:"fixed",top:0,left:0,right:0,bottom:0,background:"rgba(40,50,70,0.3)",zIndex:100,display:"flex",alignItems:"center",justifyContent:"center",padding:12,backdropFilter:"blur(4px)"}} onClick={onClose}><div className="modal-inner" style={{background:"#fff",borderRadius:22,padding:"28px 24px",maxWidth:500,width:"100%",boxShadow:"0 20px 56px rgba(60,80,120,0.12)",maxHeight:"92vh",overflowY:"auto"}} onClick={e=>e.stopPropagation()}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:22}}><h3 style={{fontSize:19,fontWeight:700,color:P.text,margin:0}}>{title}</h3><button onClick={onClose} style={{background:P.periLt,border:"none",width:38,height:38,borderRadius:10,fontSize:17,color:P.periDk,cursor:"pointer",display:"flex",alignItems:"center",justifyContent:"center"}}>✕</button></div>{children}</div></div>;}
const MI={padding:"13px 15px",border:"1.5px solid "+P.border,borderRadius:11,fontSize:15,outline:"none",fontFamily:FONT,color:P.text,background:"#FAFCF8",boxSizing:"border-box",width:"100%"};
function DlB({onClick}){return<button onClick={onClick} style={{padding:"8px 14px",background:P.periLt,border:"none",borderRadius:9,fontSize:12,fontWeight:600,color:P.periDk,cursor:"pointer",fontFamily:FONT}}>📥 엑셀</button>;}
function Toast({msg,show}){return<div style={{position:"fixed",bottom:show?30:-60,left:"50%",transform:"translateX(-50%)",background:P.periDk,color:"#fff",padding:"11px 24px",borderRadius:12,fontSize:13,fontWeight:600,fontFamily:FONT,boxShadow:"0 8px 20px rgba(91,126,174,0.2)",transition:"bottom 0.3s",zIndex:200}}>{msg}</div>;}
async function compress(file){const b64=await new Promise(r=>{const rd=new FileReader();rd.onload=()=>r(rd.result);rd.readAsDataURL(file);});const img=new Image();return new Promise(r=>{img.onload=()=>{const c=document.createElement("canvas");const max=1200;let w=img.width,h=img.height;if(w>max){h=h*(max/w);w=max;}if(h>max){w=w*(max/h);h=max;}c.width=w;c.height=h;c.getContext("2d").drawImage(img,0,0,w,h);r(c.toDataURL("image/jpeg",0.85));};img.src=b64;});}
const SDM_T=[{id:"studio",l:"📷 스튜디오",c:P.greenDk},{id:"dress",l:"👗 드레스",c:"#C62860"},{id:"makeup",l:"💄 메이크업",c:"#B0408A"}];

/* ═══ SHARE VIEW ═══ */
function ShareView({data}){const vendors=data.sdmVendors||[];const photos=(data.sdmPhotos||[]).filter(p=>p.liked);const[idx,setIdx]=useState(0);const[filter,setFilter]=useState("all");let feed=photos.map(p=>{const v=vendors.find(v=>v.id===p.vid);return{...p,vn:v?.name||"?",vt:v?.type||"studio"};});if(filter!=="all")feed=feed.filter(p=>p.vt===filter);
  return<div style={{minHeight:"100vh",background:P.bg,fontFamily:FONT,padding:"20px 16px",maxWidth:600,margin:"0 auto"}}><div style={{textAlign:"center",marginBottom:24}}><div style={{fontSize:36,marginBottom:8}}>💐</div><h1 style={{fontSize:22,fontWeight:700,color:P.periDk,margin:"0 0 4px"}}>{data.groomName} ♥ {data.brideName}</h1><p style={{fontSize:14,color:P.textSub,margin:0}}>마음에 든 스드메 사진 모음</p></div>
    {photos.length===0&&<div style={{textAlign:"center",padding:"60px 20px",color:P.textMuted}}>아직 좋아요한 사진이 없어요</div>}
    {photos.length>0&&<><div style={{display:"flex",gap:6,marginBottom:16,justifyContent:"center",flexWrap:"wrap"}}>{[{id:"all",l:"전체"},{id:"studio",l:"📷 스튜디오"},{id:"dress",l:"👗 드레스"},{id:"makeup",l:"💄 메이크업"}].map(t=><button key={t.id} onClick={()=>{setFilter(t.id);setIdx(0);}} style={{padding:"8px 16px",borderRadius:18,border:"none",fontSize:13,fontWeight:filter===t.id?700:500,background:filter===t.id?P.periDk:P.periLt,color:filter===t.id?"#fff":P.periDk,cursor:"pointer",fontFamily:FONT}}>{t.l}</button>)}</div>
      {feed.length===0&&<div style={{textAlign:"center",padding:"40px 20px",color:P.textMuted}}>이 분류에는 좋아요한 사진이 없어요</div>}
      {feed.length>0&&idx<feed.length&&(()=>{const photo=feed[idx];return<div style={{background:"#fff",borderRadius:20,overflow:"hidden",border:"1px solid "+P.border,marginBottom:14}}><div style={{position:"relative",background:"#f5f5f0"}}><img src={photo.src} style={{width:"100%",maxHeight:520,objectFit:"contain",display:"block"}} alt=""/>{idx>0&&<button onClick={()=>setIdx(idx-1)} style={{position:"absolute",left:10,top:"50%",transform:"translateY(-50%)",background:"rgba(255,255,255,0.85)",border:"none",borderRadius:18,width:40,height:40,fontSize:18,cursor:"pointer"}}>◀</button>}{idx<feed.length-1&&<button onClick={()=>setIdx(idx+1)} style={{position:"absolute",right:10,top:"50%",transform:"translateY(-50%)",background:"rgba(255,255,255,0.85)",border:"none",borderRadius:18,width:40,height:40,fontSize:18,cursor:"pointer"}}>▶</button>}<div style={{position:"absolute",bottom:10,right:10,background:"rgba(0,0,0,0.45)",color:"#fff",padding:"3px 10px",borderRadius:10,fontSize:12}}>{idx+1}/{feed.length}</div></div><div style={{padding:"14px 18px",display:"flex",alignItems:"center",gap:10}}><span style={{fontSize:22}}>❤️</span><span style={{padding:"4px 12px",borderRadius:10,fontSize:13,fontWeight:700,background:(SDM_T.find(t=>t.id===photo.vt)?.c||P.text)+"15",color:SDM_T.find(t=>t.id===photo.vt)?.c||P.text}}>{photo.vn}</span></div></div>;})()}
      {feed.length>0&&<div style={{display:"flex",gap:5,overflowX:"auto",paddingBottom:8}}>{feed.map((p,i)=><div key={p.id} onClick={()=>setIdx(i)} style={{width:56,height:56,borderRadius:9,overflow:"hidden",border:i===idx?"3px solid "+P.periDk:"2px solid transparent",cursor:"pointer",flexShrink:0}}><img src={p.src} style={{width:"100%",height:"100%",objectFit:"cover"}} alt=""/></div>)}</div>}
    </>}</div>;}

/* ═══ LOGIN / SETUP ═══ */
function LoginScreen({onLogin}){const[key,setKey]=useState("");const[isNew,setIsNew]=useState(false);const[err,setErr]=useState("");const[busy,setBusy]=useState(false);const tryLogin=async()=>{if(!key.trim()){setErr("키를 입력해주세요");return;}setBusy(true);const d=await dbLoad(key.trim());setBusy(false);if(d){onLogin(key.trim(),d);return;}setIsNew(true);setErr("");};const createNew=async()=>{setBusy(true);const d={...fresh(),isSetup:false};await dbSave(key.trim(),d);setBusy(false);onLogin(key.trim(),d);};return<div style={S.wrap}><Fl1 s={{width:140,top:-30,left:-30}}/><Fl2 s={{width:120,bottom:20,right:10}}/><div style={S.lc}><div style={{fontSize:48,marginBottom:8}}>💍</div><h1 style={{fontSize:26,fontWeight:700,color:P.periDk,margin:"0 0 6px"}}>Wedding Planner</h1><p style={{fontSize:14,color:P.textSub,margin:"0 0 28px",lineHeight:1.8}}>커플 키를 입력하면<br/>우리만의 결혼 준비 공간이 열려요</p><div style={{textAlign:"left",maxWidth:320,margin:"0 auto"}}><label style={S.lbl}>커플 키</label><input style={{...MI,fontSize:16,padding:"15px 16px"}} placeholder="예: jm-sk-2027" value={key} onChange={e=>{setKey(e.target.value);setIsNew(false);setErr("");}} onKeyDown={e=>{if(e.key==="Enter")tryLogin();}}/><p style={{fontSize:12,color:P.textMuted,margin:"8px 0 0",lineHeight:1.7}}>처음이면 키를 만드세요. 어디서든 같은 키면 기록이 있어요.</p>{err&&<p style={{color:"#D32F2F",fontSize:13,margin:"8px 0"}}>{err}</p>}{isNew?<div style={{marginTop:20,padding:20,background:`linear-gradient(135deg,${P.greenBg},${P.blueBg})`,borderRadius:16,textAlign:"center"}}><p style={{fontSize:15,color:P.text,margin:"0 0 14px"}}>✨ <b>"{key}"</b> — 새로운 키!</p><button style={{...S.btn,width:"100%"}} onClick={createNew} disabled={busy}>{busy?"생성 중...":"새로 시작하기 🌷"}</button><button onClick={()=>setIsNew(false)} style={{marginTop:10,background:"none",border:"none",color:P.textSub,fontSize:14,cursor:"pointer",fontFamily:FONT,padding:"8px 0",width:"100%"}}>← 다른 키로 변경</button></div>:<button style={{...S.btn,width:"100%",marginTop:20}} onClick={tryLogin} disabled={busy}>{busy?"확인 중...":"들어가기 →"}</button>}</div></div></div>;}
function SetupScreen({data,setData,onBack}){const[f,setF]=useState({groomName:"",brideName:"",weddingDate:"",weddingTime:"12:00"});const go=()=>{if(!f.groomName||!f.brideName||!f.weddingDate)return;setData({...data,...f,isSetup:true});};const ok=f.groomName&&f.brideName&&f.weddingDate;return<div style={S.wrap}><Fl1 s={{width:120,top:-20,left:-20}}/><div style={{...S.lc,maxWidth:440}}><div style={{fontSize:44,marginBottom:8}}>💐</div><h1 style={{fontSize:24,fontWeight:700,color:P.periDk,margin:"0 0 24px"}}>두 사람의 정보</h1><div style={{display:"flex",flexDirection:"column",gap:16,textAlign:"left"}}><div style={{display:"flex",alignItems:"center",gap:10}}><div style={{flex:1,minWidth:0}}><label style={S.lbl}>신랑 🌿</label><input style={MI} value={f.groomName} onChange={e=>setF({...f,groomName:e.target.value})} placeholder="이름"/></div><div style={{fontSize:22,color:P.peri,flexShrink:0,paddingTop:20}}>♥</div><div style={{flex:1,minWidth:0}}><label style={S.lbl}>신부 🌻</label><input style={MI} value={f.brideName} onChange={e=>setF({...f,brideName:e.target.value})} placeholder="이름"/></div></div><div style={{display:"flex",gap:10}}><div style={{flex:1,minWidth:0}}><label style={S.lbl}>결혼 예정일</label><input type="date" style={MI} value={f.weddingDate} onChange={e=>setF({...f,weddingDate:e.target.value})}/></div><div style={{flex:1,minWidth:0}}><label style={S.lbl}>예식 시간</label><input type="time" style={MI} value={f.weddingTime} onChange={e=>setF({...f,weddingTime:e.target.value})}/></div></div><button style={{...S.btn,width:"100%",opacity:ok?1:0.4}} onClick={go} disabled={!ok}>시작하기 🌷</button>{onBack&&<button onClick={onBack} style={{marginTop:8,background:"none",border:"none",color:P.textSub,fontSize:14,cursor:"pointer",fontFamily:FONT,padding:"8px 0",width:"100%"}}>← 다른 키로 로그인</button>}</div></div></div>;}

/* ═══ DASHBOARD ═══ */
function Dash({data,setTab}){const dd=getDday(data.weddingDate),tot=data.checklist.reduce((s,p)=>s+p.items.length,0),dn=data.checklist.reduce((s,p)=>s+p.items.filter(i=>i.done).length,0),pct=tot>0?Math.round(dn/tot*100):0;const bT=data.budget.reduce((s,b)=>s+(b.unitPrice||0)*(b.qty||0),0),bP=data.budget.reduce((s,b)=>s+(b.paid||0),0);const cur=data.checklist.find(p=>phaseStatus(p,data.weddingDate)==="current")||data.checklist.find(p=>phaseStatus(p,data.weddingDate)==="upcoming");const todo=cur?cur.items.filter(i=>!i.done):[];const tips=cTips(data.checklist,data.weddingDate);const upcoming=(data.keyDates||[]).filter(d=>new Date(d.date)>=new Date()).sort((a,b)=>new Date(a.date)-new Date(b.date)).slice(0,3);const[tipOpen,setTipOpen]=useState(true);
  return<div style={{display:"flex",flexDirection:"column",gap:18}}>
    <div style={S.dday}><Fl1 s={{width:150,top:-30,left:-20}}/><Fl2 s={{width:130,bottom:-15,right:30}}/><div style={{position:"relative",zIndex:1}}><div style={{fontSize:11,fontWeight:600,color:P.periDk,letterSpacing:3,marginBottom:12,opacity:0.5}}>OUR WEDDING</div><div className="couple-row" style={{display:"flex",justifyContent:"center",gap:28,marginBottom:14}}><div style={{textAlign:"center"}}><div style={{fontSize:11,color:P.blueDk,fontWeight:600,marginBottom:3}}>신랑</div><div className="couple-name" style={{fontSize:20,fontWeight:700,color:P.periDk}}>{data.groomName}</div></div><div style={{fontSize:24,color:P.lav,alignSelf:"center"}}>♥</div><div style={{textAlign:"center"}}><div style={{fontSize:11,color:P.blueDk,fontWeight:600,marginBottom:3}}>신부</div><div className="couple-name" style={{fontSize:20,fontWeight:700,color:P.periDk}}>{data.brideName}</div></div></div><div className="dday-num" style={{fontSize:64,fontWeight:800,color:P.periDk,lineHeight:1,opacity:0.8}}>{dd>0?"D-"+dd:dd===0?"D-Day 🎉":"D+"+Math.abs(dd)}</div><div style={{fontSize:15,color:P.blueDk,marginTop:12}}>{fmtDate(data.weddingDate)} {data.weddingTime}</div></div></div>
    <div className="stat-grid" style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:14}}><div onClick={()=>setTab("checklist")} style={{...S.card,background:`linear-gradient(135deg,${P.greenBg},${P.greenLt})`,cursor:"pointer"}}><div style={{fontSize:12,fontWeight:700,color:P.greenDk,marginBottom:12}}>📊 진행률</div><div style={{height:10,background:"rgba(255,255,255,0.6)",borderRadius:5,overflow:"hidden",marginBottom:12}}><div style={{height:"100%",background:`linear-gradient(90deg,${P.green},${P.blue})`,borderRadius:5,width:pct+"%"}}/></div><div style={{display:"flex",justifyContent:"space-between"}}><span style={{fontSize:32,fontWeight:800,color:P.greenDk}}>{pct}%</span><span style={{fontSize:14,color:P.greenDk,opacity:0.7,alignSelf:"flex-end"}}>{dn}/{tot}</span></div></div><div onClick={()=>setTab("budget")} style={{...S.card,background:`linear-gradient(135deg,${P.lavBg},${P.lavLt})`,cursor:"pointer"}}><div style={{fontSize:12,fontWeight:700,color:P.lavDk,marginBottom:12}}>💰 예산</div><div className="budget-main" style={{fontSize:24,fontWeight:800,color:P.lavDk,marginBottom:4}}>{fmtW(bT)}</div><div style={{fontSize:13,color:P.lav}}>지출 {fmtW(bP)}</div><div style={{fontSize:13,color:P.greenDk,fontWeight:700}}>잔여 {fmtW(bT-bP)}</div></div></div>
    <div style={{...S.card,background:`linear-gradient(135deg,${P.blueBg},${P.blueLt})`,border:"1px solid "+P.blue+"30"}}><div onClick={()=>setTipOpen(!tipOpen)} style={{display:"flex",justifyContent:"space-between",alignItems:"center",cursor:"pointer"}}><div style={{fontSize:12,fontWeight:700,color:P.blueDk}}>🤖 Tip</div><span style={{fontSize:12,color:P.blueDk,fontWeight:600}}>{tipOpen?"접기 ▲":"펼치기 ▼"}</span></div>{tipOpen&&<div style={{marginTop:10}}>{tips.map((t,i)=><div key={i} style={{fontSize:14,color:P.text,lineHeight:1.8,padding:"3px 0"}}>{t}</div>)}</div>}</div>
    {upcoming.length>0&&<div style={{...S.card,cursor:"pointer"}} onClick={()=>setTab("schedule")}><div style={{display:"flex",justifyContent:"space-between",marginBottom:12}}><span style={{fontSize:12,fontWeight:700,color:P.periDk}}>📌 다가오는 일정</span><span style={S.lnk}>전체→</span></div>{upcoming.map((d,i)=><div key={i} style={{display:"flex",justifyContent:"space-between",padding:"10px 14px",background:P.greenBg,borderRadius:12,marginBottom:6}}><span style={{fontWeight:600,fontSize:14,color:P.text}}>{d.name}</span><span style={{fontSize:13,color:P.periDk,fontWeight:600}}>{fmtDate(d.date)}</span></div>)}</div>}
    <div style={{...S.card,cursor:"pointer"}} onClick={()=>setTab("checklist")}><div style={{display:"flex",justifyContent:"space-between",marginBottom:8}}><span style={{fontSize:12,fontWeight:700,color:P.periDk}}>{cur?(cur.emoji+" "+cur.label+" — "+phaseLabel(cur,data.weddingDate)):"완료!"}</span>{cur&&<span style={S.lnk}>전체→</span>}</div>{cur&&<div style={{fontSize:12,color:P.textSub,marginBottom:10}}>기한 {phaseDeadline(cur,data.weddingDate)}</div>}{todo.slice(0,5).map(item=><div key={item.id} style={{display:"flex",alignItems:"center",gap:8,padding:"10px 12px",background:P.greenBg,borderRadius:11,marginBottom:5}}><Bg cat={item.cat}/><span style={{fontSize:14,color:P.text}}>{item.text}</span></div>)}{todo.length>5&&<div style={{fontSize:13,color:P.textMuted,textAlign:"center"}}>외 {todo.length-5}개</div>}</div>
  </div>;}

/* ═══ CHECKLIST — dynamic dates ═══ */
function CLTab({data,setData}){const wd=data.weddingDate;const[memoId,setMemoId]=useState(null);const[memoTxt,setMemoTxt]=useState("");const[addPi,setAddPi]=useState(null);const[addF,setAddF]=useState({text:"",cat:"etc",customCatName:"",note:""});const toggle=(pi,id)=>{setData({...data,checklist:data.checklist.map((p,i)=>i!==pi?p:{...p,items:p.items.map(it=>it.id===id?{...it,done:!it.done}:it)})});};const saveMemo=()=>{if(!memoId)return;setData({...data,checklist:data.checklist.map((p,i)=>i!==memoId.pi?p:{...p,items:p.items.map(it=>it.id===memoId.id?{...it,memo:memoTxt}:it)})});setMemoId(null);};const addItem=()=>{if(!addF.text||addPi===null)return;const isCust=addF.cat==="__custom__";setData({...data,checklist:data.checklist.map((p,i)=>i!==addPi?p:{...p,items:[...p.items,{id:"c"+Date.now(),text:addF.text,cat:isCust?"__custom__":addF.cat,customCatName:isCust?addF.customCatName:"",note:addF.note,done:false,memo:"",custom:true}]})});setAddPi(null);};const rmItem=(pi,id)=>{if(!confirm("정말 삭제하시겠습니까?"))return;setData({...data,checklist:data.checklist.map((p,i)=>i!==pi?p:{...p,items:p.items.filter(it=>it.id!==id)})});};const dlCL=()=>{const rows=[];data.checklist.forEach(ph=>{ph.items.forEach(i=>{rows.push([ph.label,phaseLabel(ph,wd),phaseDeadline(ph,wd),CAT[i.cat]?CAT[i.cat].n:(i.customCatName||"기타"),i.text,i.done?"완료":"미완료",i.memo||""]);});});dlCSV("체크리스트",["단계","시기","기한","카테고리","항목","상태","메모"],rows);};
  return<div style={S.tab}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:20,flexWrap:"wrap",gap:8}}><h2 style={{...S.th,margin:0}}>🌿 체크리스트</h2><DlB onClick={dlCL}/></div>
    <Modal title="메모" open={memoId!==null} onClose={()=>setMemoId(null)}><div style={{marginBottom:18}}><textarea style={{...MI,minHeight:110,resize:"vertical"}} placeholder="업체 연락처, 가격, 주의사항 등" value={memoTxt} onChange={e=>setMemoTxt(e.target.value)}/></div><button style={{...S.btn,width:"100%"}} onClick={saveMemo}>저장</button></Modal>
    <Modal title="항목 추가" open={addPi!==null} onClose={()=>setAddPi(null)}><div style={{marginBottom:18}}><label style={S.lbl}>할 일</label><input style={MI} placeholder="예: 피부관리" value={addF.text} onChange={e=>setAddF({...addF,text:e.target.value})}/></div><div style={{marginBottom:18}}><label style={S.lbl}>카테고리</label><select style={MI} value={addF.cat} onChange={e=>setAddF({...addF,cat:e.target.value})}>{Object.entries(CAT).map(([k,c])=><option key={k} value={k}>{c.ic} {c.n}</option>)}<option value="__custom__">✏️ 직접 입력</option></select></div>{addF.cat==="__custom__"&&<div style={{marginBottom:18}}><label style={S.lbl}>카테고리명</label><input style={MI} value={addF.customCatName} onChange={e=>setAddF({...addF,customCatName:e.target.value})}/></div>}<button style={{...S.btn,width:"100%"}} onClick={addItem}>추가</button></Modal>
    {wd&&<div style={{...S.card,marginBottom:20,background:`linear-gradient(135deg,${P.greenBg},${P.blueBg})`,textAlign:"center",padding:"16px 20px"}}><div style={{fontSize:13,color:P.periDk,fontWeight:600}}>결혼일 기준 자동 역산 일정</div><div style={{fontSize:12,color:P.textSub,marginTop:4}}>{(()=>{const avail=getAvailableMonths(wd);return avail>=BASE_PREP_MONTHS?"준비 기간 여유 있음 ("+avail+"개월) — 기본 일정 적용":"준비 기간 "+avail+"개월 — 기본 14개월 일정을 비율로 자동 압축";})()}</div></div>}
    <div style={{display:"flex",flexDirection:"column",gap:20}}>
      {data.checklist.map((ph,pi)=>{const st=phaseStatus(ph,wd),allD=ph.items.every(i=>i.done),dc=ph.items.filter(i=>i.done).length;const cg={};ph.items.forEach(it=>{const key=it.cat==="__custom__"?(it.customCatName||"기타"):it.cat;if(!cg[key])cg[key]={cat:it.cat,cn:it.customCatName,items:[]};cg[key].items.push(it);});
        const deadlineStr=phaseDeadline(ph,wd);const isOverdue=st==="past"&&!allD;
        return<div key={pi} style={{...S.card,borderLeft:"4px solid "+(isOverdue?"#E57373":st==="current"?P.blue:st==="past"?P.blueLt:"#E0E0E0"),padding:"20px 18px"}}>
          <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:8,flexWrap:"wrap",gap:6}}><div style={{display:"flex",alignItems:"center",gap:8}}><span style={{width:26,height:26,borderRadius:"50%",display:"flex",alignItems:"center",justifyContent:"center",fontSize:12,fontWeight:700,color:"#fff",background:allD?P.green:isOverdue?"#E57373":st==="current"?P.blue:"#E0E0E0"}}>{allD?"✓":""}</span><span style={{fontSize:16,fontWeight:700,color:P.text}}>{ph.emoji} {ph.label}</span><span style={{fontSize:13,color:P.textMuted}}>{dc}/{ph.items.length}</span></div><button style={{...S.ebtn,fontSize:11,padding:"4px 10px"}} onClick={()=>{setAddF({text:"",cat:"etc",customCatName:"",note:""});setAddPi(pi);}}>+ 추가</button></div>
          <div style={{fontSize:12,color:isOverdue?"#E57373":P.textSub,marginBottom:14,paddingLeft:34,fontWeight:isOverdue?600:400}}>📅 {phaseLabel(ph,wd)} · 기한 {deadlineStr}{isOverdue?" ⚠️ 지연됨":""}</div>
          {Object.entries(cg).map(([key,g])=>{const c=CAT[g.cat];return<div key={key} style={{marginBottom:12}}><div style={{fontSize:12,fontWeight:700,color:c?c.fg:P.blueDk,marginBottom:6,paddingLeft:3}}>{c?`${c.ic} ${c.n}`:`✏️ ${g.cn||key}`}</div>{g.items.map(item=><div key={item.id} className="cl-item-wrap" style={{display:"flex",gap:10,alignItems:"flex-start",padding:"10px 12px",borderRadius:11,background:item.done?"#F8F8F8":P.greenBg,opacity:item.done?0.4:1,marginBottom:4,border:"1px solid "+(item.done?"#F0F0F0":P.border)}}><div style={{width:22,height:22,borderRadius:7,border:"2px solid "+(item.done?P.green:P.peri),background:item.done?P.green:"#fff",display:"flex",alignItems:"center",justifyContent:"center",fontSize:12,fontWeight:700,color:"#fff",flexShrink:0,cursor:"pointer"}} onClick={()=>toggle(pi,item.id)}>{item.done?"✓":""}</div><div style={{flex:1,cursor:"pointer",minWidth:0}} onClick={()=>{setMemoId({pi,id:item.id});setMemoTxt(item.memo||"");}}><span style={{textDecoration:item.done?"line-through":"none",fontSize:14,color:P.text}}>{item.text}</span>{item.memo&&<div style={{fontSize:12,color:P.periDk,marginTop:3,background:P.periLt,padding:"4px 8px",borderRadius:6}}>📝 {item.memo}</div>}</div>{item.custom&&<button style={{...S.dbtn,fontSize:14}} onClick={()=>rmItem(pi,item.id)}>✕</button>}</div>)}</div>;})}
        </div>;})}
    </div></div>;}

/* ═══ SDM ═══ */
function SdmTab({data,setData,coupleKey,showT}){const[show,setShow]=useState(false);const[editVid,setEditVid]=useState(null);const[filter,setFilter]=useState("all");const[f,setF]=useState({name:"",type:"studio",price:"",insta:"",website:"",memo:""});const[ef,setEf]=useState({name:"",type:"studio",price:"",insta:"",website:"",memo:""});const[photoIdx,setPhotoIdx]=useState(0);const vendors=data.sdmVendors||[];const photos=data.sdmPhotos||[];
  /* ── Concept Board ── */
  const[cbOpen,setCbOpen]=useState(false);const[cbRecip,setCbRecip]=useState("studio");const[cbNotes,setCbNotes]=useState("");const[cbStep,setCbStep]=useState("select");const[cbResult,setCbResult]=useState(null);
  const CB_BASE="절대 길게 쓰지 마세요. 번호 리스트, 키워드, 체크리스트 형태만 사용. 문장형 금지.\n\n중요 규칙:\n- 사진에서 분석할 수 있는 내용은 분석하여 작성\n- 파악 안 되는 항목은 가이드라인: [여기에 OOO을 적어주세요] 형태로\n\nJSON 형식으로만 응답. 백틱/마크다운 금지. 문자열 안에 줄바꿈은 반드시 \\n으로.\n{\"title\":\"제목\",\"summary\":\"한줄요약\",\"mood\":\"키워드\",\"sections\":[{\"heading\":\"섹션명\",\"body\":\"내용\"}],\"concepts\":[{\"name\":\"컨셉명\",\"photoIndices\":[0,1],\"details\":\"내용\"}]}";
  const CB_TYPES={studio:{l:"📷 스튜디오 작가님",sys:CB_BASE+"\n\nsections 구성:\n1. 신부 의상 총 N벌 - 번호리스트\n2. 신랑 의상 총 N벌 - 번호리스트\n3. 신부 헤어 - 키워드 (파악안되면 [여기에 원하는 헤어스타일 적어주세요])\n4. 신랑 헤어 - 키워드\n5. 활용소품 - 번호리스트\n\nconcepts 배열 (중요!):\n- 사진들을 분석해서 로케이션/컨셉별로 그룹핑\n- photoIndices: 해당 컨셉에 맞는 사진 번호(0부터 시작)\n- details: 해당 컨셉의 의상/소품/포즈를 짧은 체크리스트로\n- 예: {\"name\":\"초록들판\",\"photoIndices\":[0,2],\"details\":\"신부: 노란드레스\\n신랑: 블랙\\n소품: 풍선다발\\n포즈: 뛰는샷, 후라이샷\"}\n- 사진이 비슷한 분위기면 같은 컨셉으로 묶기\n- 최소 2개 ~ 최대 5개 컨셉"},
    dress:{l:"👗 드레스샵 실장님",sys:CB_BASE+"\n\nsections:\n1. 선호 드레스 스타일 - 라인, 넥라인, 소매\n2. 소재 & 디테일\n3. 원하는 분위기 - 키워드\n4. 피하고 싶은 스타일 (파악안되면 가이드라인)\n5. 참고사항\n\nconcepts: 사진별로 드레스 스타일을 그룹핑\n- name: 드레스 스타일명 (예: 클래식 A라인, 슬립드레스)\n- photoIndices: 해당 스타일 사진번호\n- details: 해당 드레스의 특징 키워드"},
    makeup:{l:"💄 메이크업 아티스트님",sys:CB_BASE+"\n\nsections:\n1. 전체 무드 - 키워드\n2. 베이스 메이크업\n3. 아이 메이크업\n4. 립 & 치크\n5. 헤어 스타일\n6. 피하고 싶은 것 (파악안되면 가이드라인)\n\nconcepts: 사진별 메이크업 스타일 그룹핑\n- name: 메이크업 무드명\n- photoIndices: 해당 사진번호\n- details: 해당 메이크업 특징"}};
  const compressForAI=async(src)=>{return new Promise(r=>{const img=new Image();img.onload=()=>{const c=document.createElement("canvas");const max=400;let w=img.width,h=img.height;if(w>max){h=h*(max/w);w=max;}if(h>max){w=w*(max/h);h=max;}c.width=w;c.height=h;c.getContext("2d").drawImage(img,0,0,w,h);const d=c.toDataURL("image/jpeg",0.6);r(d.split(",")[1]);};img.onerror=()=>r(null);img.src=src;});};
  const cbLikedByType=(type)=>{return photos.filter(p=>{if(!p.liked)return false;const v=vendors.find(v=>v.id===p.vid);return v&&v.type===type;});};
  const cbAnalyze=async()=>{const liked=cbLikedByType(cbRecip);if(liked.length===0){showT("해당 카테고리에 좋아요한 사진이 없어요");return;}setCbStep("loading");try{const smallImgs=[];for(const p of liked.slice(0,4)){const b64=await compressForAI(p.src);if(b64)smallImgs.push({type:"image",source:{type:"base64",media_type:"image/jpeg",data:b64}});}if(smallImgs.length===0){setCbStep("error");return;}const userMsg=[...smallImgs,{type:"text",text:"예비 신부의 메모/요청사항: "+(cbNotes||"특별한 요청 없음")+"\n\n위 레퍼런스 사진들을 분석하여 컨셉 보드를 JSON으로 작성해주세요. 한국어로 작성하세요."}];const body=JSON.stringify({system:CB_TYPES[cbRecip].sys,messages:[{role:"user",content:userMsg}]});
    /* Try serverless function first (Vercel), fallback to direct API (Claude preview) */
    let res;try{res=await fetch("/api/concept-board",{method:"POST",headers:{"Content-Type":"application/json"},body});if(!res.ok)throw new Error("serverless "+res.status);}catch(e1){console.log("Serverless failed, trying direct API...",e1.message);res=await fetch("https://api.anthropic.com/v1/messages",{method:"POST",headers:{"Content-Type":"application/json","anthropic-version":"2023-06-01"},body:JSON.stringify({model:"claude-sonnet-4-20250514",max_tokens:2000,system:CB_TYPES[cbRecip].sys,messages:[{role:"user",content:userMsg}]})});}
    if(!res.ok){const errText=await res.text();console.error("API error:",res.status,errText);setCbStep("error");return;}const d=await res.json();console.log("API response:",d);const txt=d.content?.map(c=>c.text||"").join("")||"";let clean=txt.replace(/```json|```/g,"").trim();
    /* Robust JSON parsing: fix common issues */
    try{var parsed=JSON.parse(clean);}catch(e1){console.warn("JSON fix attempt...",e1.message);clean=clean.replace(/[\x00-\x1F]/g," ").replace(/,\s*}/g,"}").replace(/,\s*]/g,"]");try{parsed=JSON.parse(clean);}catch(e2){console.error("JSON parse failed:",e2,clean.slice(0,500));setCbStep("error");return;}}
    setCbResult(parsed);setCbStep("result");}catch(e){console.error("cbAnalyze error:",e);setCbStep("error");}};
  const cbDownloadPPT=async()=>{if(!cbResult||typeof PptxGenJS==="undefined")return;const pptx=new PptxGenJS();pptx.defineLayout({name:"WIDE",width:13.33,height:7.5});pptx.layout="WIDE";const liked=cbLikedByType(cbRecip);
    const C={bg:"F8FAF5",card:"FFFFFF",accent:"5B7EAE",accent2:"7BA23A",accent3:"B0A0CC",warm:"C62860",text:"3A3A50",sub:"8A8A9E",guideline:"6EC8E4"};
    const addBar=(sl,c)=>{sl.addShape(pptx.ShapeType.rect,{x:0,y:0,w:"100%",h:0.06,fill:{color:c||C.accent}});};
    const fmtTxt=(body,x,y,w,h,sl)=>{const lines=(body||"").split("\n");const runs=[];lines.forEach((ln,i)=>{if(i>0)runs.push({text:"\n",options:{fontSize:12}});const isGuide=ln.includes("[")||ln.includes("「");runs.push({text:ln,options:{fontSize:isGuide?11:12,fontFace:"Pretendard",color:isGuide?C.guideline:C.text,italic:isGuide}});});sl.addText(runs,{x,y,w,h,lineSpacingMultiple:1.55,valign:"top"});};

    /* Slide 1: Title card */
    let s=pptx.addSlide();s.background={color:C.bg};addBar(s);
    s.addShape(pptx.ShapeType.rect,{x:0.5,y:0.4,w:12.3,h:3.0,fill:{color:C.card},rectRadius:0.2,shadow:{type:"outer",blur:6,offset:3,color:"000000",opacity:0.06}});
    s.addText(cbResult.title||"컨셉 보드",{x:1.0,y:0.7,w:10,h:0.8,fontSize:30,fontFace:"Pretendard",color:C.accent,bold:true});
    s.addText(cbResult.summary||"",{x:1.0,y:1.5,w:10,h:0.5,fontSize:14,fontFace:"Pretendard",color:C.sub});
    s.addText("MOOD  "+((cbResult.mood||"").toUpperCase()),{x:1.0,y:2.2,w:10,h:0.5,fontSize:13,fontFace:"Pretendard",color:C.accent,bold:true,charSpacing:2});
    /* Reference photos strip */
    if(liked.length>0){const strip=Math.min(liked.length,4),pw=2.8;liked.slice(0,strip).forEach((p,i)=>{try{s.addImage({data:p.src,x:0.5+i*(pw+0.2),y:3.8,w:pw,h:3.2,sizing:{type:"cover",w:pw,h:3.2},rounding:true});}catch(e){}});}

    /* Slide 2+: Sections (2 per slide) */
    const secs=cbResult.sections||[];for(let i=0;i<secs.length;i+=2){s=pptx.addSlide();s.background={color:C.bg};addBar(s,C.accent2);const sec1=secs[i],sec2=secs[i+1];
      if(sec2){s.addShape(pptx.ShapeType.rect,{x:0.4,y:0.4,w:6.1,h:6.6,fill:{color:C.card},rectRadius:0.15,shadow:{type:"outer",blur:5,offset:2,color:"000000",opacity:0.05}});s.addText(sec1.heading,{x:0.7,y:0.6,w:5.5,h:0.5,fontSize:16,fontFace:"Pretendard",color:C.accent,bold:true});fmtTxt(sec1.body,0.7,1.3,5.5,5.4,s);s.addShape(pptx.ShapeType.rect,{x:6.8,y:0.4,w:6.1,h:6.6,fill:{color:C.card},rectRadius:0.15,shadow:{type:"outer",blur:5,offset:2,color:"000000",opacity:0.05}});s.addText(sec2.heading,{x:7.1,y:0.6,w:5.5,h:0.5,fontSize:16,fontFace:"Pretendard",color:C.accent,bold:true});fmtTxt(sec2.body,7.1,1.3,5.5,5.4,s);}
      else{s.addShape(pptx.ShapeType.rect,{x:0.4,y:0.4,w:12.5,h:6.6,fill:{color:C.card},rectRadius:0.15,shadow:{type:"outer",blur:5,offset:2,color:"000000",opacity:0.05}});s.addText(sec1.heading,{x:0.7,y:0.6,w:11,h:0.5,fontSize:16,fontFace:"Pretendard",color:C.accent,bold:true});fmtTxt(sec1.body,0.7,1.3,11.5,5.4,s);}}

    /* Concept slides: each concept gets its own slide with photos */
    const concepts=cbResult.concepts||[];const colors=[C.accent,C.accent2,C.accent3,C.warm,"C8960A"];
    concepts.forEach((con,ci)=>{s=pptx.addSlide();s.background={color:C.bg};const cc=colors[ci%colors.length];addBar(s,cc);
      s.addText("CONCEPT "+(ci+1),{x:0.5,y:0.3,w:3,h:0.4,fontSize:11,fontFace:"Pretendard",color:cc,bold:true,charSpacing:3});
      s.addText(con.name,{x:0.5,y:0.7,w:12,h:0.6,fontSize:22,fontFace:"Pretendard",color:C.text,bold:true});
      /* Photos for this concept */
      const cPhotos=(con.photoIndices||[]).map(idx=>liked[idx]).filter(Boolean);const pCount=Math.min(cPhotos.length,3);
      if(pCount>0&&pCount<=2){/* Photos left, details right */
        const pw=pCount===1?4.5:3.2;cPhotos.slice(0,pCount).forEach((p,i)=>{try{s.addImage({data:p.src,x:0.5+i*(pw+0.2),y:1.5,w:pw,h:4.5,sizing:{type:"cover",w:pw,h:4.5},rounding:true});}catch(e){}});
        if(con.details){const dx=pCount===1?5.5:7.0;s.addShape(pptx.ShapeType.rect,{x:dx,y:1.5,w:13.33-dx-0.5,h:5.5,fill:{color:"FFFFFF"},rectRadius:0.12,shadow:{type:"outer",blur:4,offset:2,color:"000000",opacity:0.05}});s.addShape(pptx.ShapeType.rect,{x:dx,y:1.5,w:0.08,h:5.5,fill:{color:cc}});fmtTxt(con.details,dx+0.4,1.7,13.33-dx-1.2,5.1,s);}
      }else if(pCount===3){/* 3 photos top, details bottom */
        const pw=3.8;cPhotos.slice(0,3).forEach((p,i)=>{try{s.addImage({data:p.src,x:0.5+i*(pw+0.2),y:1.5,w:pw,h:3.2,sizing:{type:"cover",w:pw,h:3.2},rounding:true});}catch(e){}});
        if(con.details){s.addShape(pptx.ShapeType.rect,{x:0.5,y:5.1,w:12.3,h:2.0,fill:{color:"FFFFFF"},rectRadius:0.12,shadow:{type:"outer",blur:4,offset:2,color:"000000",opacity:0.05}});s.addShape(pptx.ShapeType.rect,{x:0.5,y:5.1,w:12.3,h:0.06,fill:{color:cc}});fmtTxt(con.details,0.8,5.3,11.7,1.7,s);}
      }else{/* No photos, full details */
        if(con.details){s.addShape(pptx.ShapeType.rect,{x:0.5,y:1.5,w:12.3,h:5.5,fill:{color:"FFFFFF"},rectRadius:0.12,shadow:{type:"outer",blur:4,offset:2,color:"000000",opacity:0.05}});s.addShape(pptx.ShapeType.rect,{x:0.5,y:1.5,w:0.08,h:5.5,fill:{color:cc}});fmtTxt(con.details,0.9,1.7,11.5,5.1,s);}
      }});

    const fn=(cbResult.title||"concept-board").replace(/\s+/g,"_");pptx.writeFile({fileName:fn+".pptx"}).then(()=>showT("PPT 다운로드 완료!"));};
  const cbClose=()=>{setCbOpen(false);setCbStep("select");setCbResult(null);};
  const addVendor=()=>{if(!f.name)return;setData({...data,sdmVendors:[...vendors,{id:"v"+Date.now(),...f}]});setF({name:"",type:"studio",price:"",insta:"",website:"",memo:""});setShow(false);};const editVendor=()=>{setData({...data,sdmVendors:vendors.map(v=>v.id===editVid?{...v,...ef}:v)});setEditVid(null);};const rmVendor=id=>{if(!confirm("정말 삭제하시겠습니까? 업체와 등록된 사진이 모두 삭제됩니다."))return;setData({...data,sdmVendors:vendors.filter(v=>v.id!==id),sdmPhotos:photos.filter(p=>p.vid!==id)});};const openEditV=v=>{setEditVid(v.id);setEf({name:v.name,type:v.type,price:v.price||"",insta:v.insta||"",website:v.website||"",memo:v.memo||""});};
  const addPhotos=async(vid,e)=>{const files=Array.from(e.target.files).slice(0,8);const np=[];for(const file of files){const src=await compress(file);np.push({id:"p"+Date.now()+Math.random().toString(36).slice(2),vid,src,liked:false});}setData({...data,sdmPhotos:[...photos,...np]});e.target.value="";};const toggleLike=pid=>{setData({...data,sdmPhotos:photos.map(p=>p.id===pid?{...p,liked:!p.liked}:p)});};const rmPhoto=pid=>{setData({...data,sdmPhotos:photos.filter(p=>p.id!==pid)});};
  let feed=photos.map(p=>{const v=vendors.find(v=>v.id===p.vid);return{...p,vn:v?.name||"?",vt:v?.type||"studio"};});if(filter==="liked")feed=feed.filter(p=>p.liked);else if(filter!=="all")feed=feed.filter(p=>p.vt===filter);const likedCount=photos.filter(p=>p.liked).length;const shareUrl=typeof window!=="undefined"?window.location.origin+window.location.pathname+"?share="+encodeURIComponent(coupleKey||""):"";
  const vF=(v,sv)=><><div style={{marginBottom:18}}><label style={S.lbl}>업체명</label><input style={MI} placeholder="예: 보네르" value={v.name} onChange={e=>sv({...v,name:e.target.value})}/></div><div style={{marginBottom:18}}><label style={S.lbl}>분류</label><select style={MI} value={v.type} onChange={e=>sv({...v,type:e.target.value})}>{SDM_T.map(t=><option key={t.id} value={t.id}>{t.l}</option>)}</select></div><div style={{marginBottom:18}}><label style={S.lbl}>가격대</label><input style={MI} placeholder="예: 180~250만원" value={v.price} onChange={e=>sv({...v,price:e.target.value})}/></div><div style={{marginBottom:18}}><label style={S.lbl}>인스타 (선택)</label><input style={MI} value={v.insta} onChange={e=>sv({...v,insta:e.target.value})}/></div><div style={{marginBottom:18}}><label style={S.lbl}>홈페이지 (선택)</label><input style={MI} value={v.website} onChange={e=>sv({...v,website:e.target.value})}/></div><div style={{marginBottom:18}}><label style={S.lbl}>메모</label><textarea style={{...MI,minHeight:50,resize:"vertical"}} value={v.memo} onChange={e=>sv({...v,memo:e.target.value})}/></div></>;
  return<div style={S.tab}><h2 style={S.th}>💐 스드메 비교</h2>
    <div style={{display:"flex",gap:8,marginBottom:14,flexWrap:"wrap"}}><button style={{...S.btn,padding:"10px 18px",fontSize:13}} onClick={()=>{setF({name:"",type:"studio",price:"",insta:"",website:"",memo:""});setShow(true);}}>+ 업체 등록</button>{likedCount>0&&<button style={{padding:"10px 18px",background:P.lavLt,color:P.lavDk,border:"none",borderRadius:12,fontSize:13,fontWeight:600,cursor:"pointer",fontFamily:FONT}} onClick={()=>{navigator.clipboard.writeText(shareUrl).then(()=>showT("공유 링크 복사됨!")).catch(()=>{});}}>🔗 좋아요 {likedCount}개 공유</button>}{likedCount>0&&<button style={{padding:"10px 18px",background:"linear-gradient(135deg,#FCE4EC,#E4DFF0)",color:P.lavDk,border:"none",borderRadius:12,fontSize:13,fontWeight:600,cursor:"pointer",fontFamily:FONT}} onClick={()=>setCbOpen(true)}>✨ 컨셉 보드</button>}</div>
    {/* ── Concept Board Modal ── */}
    <Modal title={cbStep==="result"?(cbResult?.title||"컨셉 보드"):"✨ 컨셉 보드 만들기"} open={cbOpen} onClose={cbClose}>
      {cbStep==="select"&&<><div style={{marginBottom:18}}><label style={S.lbl}>누구에게 보낼 컨셉 보드인가요?</label><div style={{display:"flex",gap:8,flexWrap:"wrap"}}>{Object.entries(CB_TYPES).map(([k,v])=><button key={k} onClick={()=>setCbRecip(k)} style={{padding:"10px 16px",borderRadius:12,border:"none",fontSize:14,fontWeight:cbRecip===k?700:500,background:cbRecip===k?P.periDk:P.periLt,color:cbRecip===k?"#fff":P.periDk,cursor:"pointer",fontFamily:FONT}}>{v.l}</button>)}</div></div>
        <div style={{marginBottom:18}}><label style={S.lbl}>원하는 스타일이나 요청사항</label><textarea style={{...MI,minHeight:80,resize:"vertical"}} placeholder={"자유롭게 적어주세요!\n예: 깔끔하고 자연스러운 분위기, 초록들판+꽃밭 컨셉 원해요, 노란 드레스 포함, 풍선 소품 사용하고 싶어요\n\n비워두셔도 괜찮아요 — 사진만으로도 분석해드려요!"} value={cbNotes} onChange={e=>setCbNotes(e.target.value)}/></div>
        {(()=>{const cbPhotos=cbLikedByType(cbRecip);return<div style={{marginBottom:18,padding:"14px 16px",background:cbPhotos.length>0?P.greenBg:"#FFF3E0",borderRadius:12}}><div style={{fontSize:13,fontWeight:600,color:cbPhotos.length>0?P.greenDk:"#E65100",marginBottom:6}}>{cbPhotos.length>0?"포함될 "+CB_TYPES[cbRecip].l+" 사진 "+cbPhotos.length+"장":"⚠️ "+CB_TYPES[cbRecip].l+" 카테고리에 좋아요한 사진이 없어요"}</div>{cbPhotos.length>0&&<div style={{display:"flex",gap:4,overflowX:"auto"}}>{cbPhotos.slice(0,6).map(p=><div key={p.id} style={{width:48,height:48,borderRadius:8,overflow:"hidden",flexShrink:0}}><img src={p.src} style={{width:"100%",height:"100%",objectFit:"cover"}} alt=""/></div>)}</div>}{cbPhotos.length>4&&<div style={{fontSize:11,color:P.textMuted,marginTop:4}}>최대 4장까지 AI 분석에 포함돼요</div>}{cbPhotos.length===0&&<div style={{fontSize:12,color:P.textSub,marginTop:4}}>스드메 탭에서 해당 카테고리 업체의 사진에 좋아요를 눌러주세요</div>}</div>;})()}
        <button style={{...S.btn,width:"100%"}} onClick={cbAnalyze}>🤖 AI 분석 시작</button></>}
      {cbStep==="loading"&&<div style={{textAlign:"center",padding:"40px 20px"}}><div style={{fontSize:36,marginBottom:12}}>🤖</div><div style={{fontSize:16,fontWeight:600,color:P.periDk,marginBottom:8}}>사진을 분석하고 있어요...</div><div style={{fontSize:14,color:P.textSub}}>30초~1분 정도 걸릴 수 있어요</div></div>}
      {cbStep==="error"&&<div style={{textAlign:"center",padding:"30px 20px"}}><div style={{fontSize:15,color:"#D32F2F",marginBottom:12}}>분석 중 오류가 발생했어요.</div><div style={{fontSize:13,color:P.textSub,marginBottom:16}}>사진 크기가 크거나 네트워크 문제일 수 있어요.<br/>좋아요 사진 수를 줄이고 다시 시도해보세요.</div><button style={{...S.btn}} onClick={()=>setCbStep("select")}>다시 시도</button></div>}
      {cbStep==="result"&&cbResult&&<><div style={{marginBottom:18,padding:"14px 16px",background:`linear-gradient(135deg,${P.blueBg},${P.lavBg})`,borderRadius:14}}><div style={{fontSize:14,fontWeight:600,color:P.periDk,marginBottom:6}}>{cbResult.summary}</div><div style={{fontSize:13,color:P.blueDk,fontStyle:"italic"}}>Mood: {cbResult.mood}</div></div>
        {(cbResult.sections||[]).map((sec,i)=><div key={i} style={{marginBottom:14,padding:"14px 16px",background:P.greenBg,borderRadius:12}}><div style={{fontSize:14,fontWeight:700,color:P.periDk,marginBottom:6}}>{sec.heading}</div><div style={{fontSize:14,color:P.text,lineHeight:1.7,whiteSpace:"pre-wrap"}}>{(sec.body||"").split("\n").map((line,j)=><div key={j} style={line.includes("[")||line.includes("「")?{color:P.blueDk,fontStyle:"italic",background:P.blueLt,padding:"4px 8px",borderRadius:6,marginTop:4,fontSize:13}:{}}>{line}</div>)}</div></div>)}
        {/* Concepts with photos */}
        {(cbResult.concepts||[]).length>0&&<div style={{fontSize:14,fontWeight:700,color:P.periDk,marginBottom:10,marginTop:6}}>📸 촬영 컨셉별 정리</div>}
        {(cbResult.concepts||[]).map((con,ci)=>{const cLiked=cbLikedByType(cbRecip);const cPhotos=(con.photoIndices||[]).map(idx=>cLiked[idx]).filter(Boolean);return<div key={ci} style={{marginBottom:16,padding:"14px 16px",background:"#fff",borderRadius:14,border:"2px solid "+P.periLt}}>
          <div style={{fontSize:15,fontWeight:700,color:P.periDk,marginBottom:8}}>컨셉 {ci+1}. {con.name}</div>
          {cPhotos.length>0&&<div style={{display:"flex",gap:6,overflowX:"auto",marginBottom:10}}>{cPhotos.map((p,i)=><div key={i} style={{width:80,height:80,borderRadius:10,overflow:"hidden",flexShrink:0}}><img src={p.src} style={{width:"100%",height:"100%",objectFit:"cover"}} alt=""/></div>)}</div>}
          <div style={{fontSize:13,color:P.text,lineHeight:1.7,whiteSpace:"pre-wrap"}}>{(con.details||"").split("\n").map((line,j)=><div key={j} style={line.includes("[")||line.includes("「")?{color:P.blueDk,fontStyle:"italic",fontSize:12}:{}}>{line}</div>)}</div>
        </div>;})}
        <div style={{display:"flex",gap:8,flexWrap:"wrap"}}><button style={{...S.btn,flex:1}} onClick={cbDownloadPPT}>📥 PPT 다운로드</button><button style={{padding:"13px 18px",background:P.periLt,color:P.periDk,border:"none",borderRadius:12,fontSize:14,fontWeight:600,cursor:"pointer",fontFamily:FONT}} onClick={()=>{setCbStep("select");setCbResult(null);}}>다시 만들기</button></div></>}
    </Modal>
    <Modal title="업체 등록" open={show} onClose={()=>setShow(false)}>{vF(f,setF)}<button style={{...S.btn,width:"100%"}} onClick={addVendor}>등록</button></Modal>
    <Modal title="업체 수정" open={editVid!==null} onClose={()=>setEditVid(null)}>{vF(ef,setEf)}<button style={{...S.btn,width:"100%"}} onClick={editVendor}>저장</button></Modal>
    {vendors.length>0&&<div style={{...S.card,marginBottom:18,padding:"16px 18px"}}><div style={{fontSize:12,fontWeight:700,color:P.periDk,marginBottom:10}}>등록 업체</div>{vendors.map(v=>{const t=SDM_T.find(x=>x.id===v.type);const pc=photos.filter(p=>p.vid===v.id).length;return<div key={v.id} style={{display:"flex",justifyContent:"space-between",alignItems:"center",padding:"10px 12px",background:P.greenBg,borderRadius:12,marginBottom:6,flexWrap:"wrap",gap:6}}><div style={{display:"flex",alignItems:"center",gap:8,flex:1,minWidth:0}}><span style={{fontSize:13,fontWeight:700,color:t?.c}}>{t?.l?.slice(0,2)}</span><span style={{fontWeight:600,color:P.text,fontSize:14}}>{v.name}</span><span style={{fontSize:12,color:P.textMuted}}>({pc}장)</span></div><div className="sdm-vendor-btns" style={{display:"flex",gap:4,alignItems:"center",flexShrink:0}}><label style={{padding:"5px 10px",background:P.blueLt,color:P.blueDk,borderRadius:7,fontSize:11,fontWeight:600,cursor:"pointer"}}>📷<input type="file" accept="image/*" multiple style={{display:"none"}} onChange={e=>addPhotos(v.id,e)}/></label><a href={"https://search.naver.com/search.naver?query="+encodeURIComponent(v.name+" 웨딩")} target="_blank" rel="noopener" style={{fontSize:12,padding:"4px 7px",background:"#E8F5E9",borderRadius:5,color:"#2E7D32",fontWeight:600,textDecoration:"none"}}>N</a><a href={"https://www.instagram.com/explore/tags/"+encodeURIComponent(v.name)} target="_blank" rel="noopener" style={{fontSize:12,padding:"4px 7px",background:"#FCE4EC",borderRadius:5,color:"#C62860",fontWeight:600,textDecoration:"none"}}>IG</a><button style={{...S.ebtn,padding:"4px 10px",fontSize:11}} onClick={()=>openEditV(v)}>수정</button><button style={S.dbtn} onClick={()=>rmVendor(v.id)}>✕</button></div></div>;})}<p style={{fontSize:11,color:P.textMuted,margin:"6px 0 0"}}>업체당 최대 8장 / 고화질(1200px)</p></div>}
    {photos.length>0&&<div style={{display:"flex",gap:6,marginBottom:16,flexWrap:"wrap"}}>{[{id:"all",l:"전체"},{id:"studio",l:"📷"},{id:"dress",l:"👗"},{id:"makeup",l:"💄"},{id:"liked",l:"❤️"}].map(t=><button key={t.id} onClick={()=>{setFilter(t.id);setPhotoIdx(0);}} style={{padding:"8px 14px",borderRadius:18,border:"none",fontSize:13,fontWeight:filter===t.id?700:500,background:filter===t.id?P.periDk:P.periLt,color:filter===t.id?"#fff":P.periDk,cursor:"pointer",fontFamily:FONT}}>{t.l}{t.id==="liked"&&likedCount>0?" "+likedCount:""}</button>)}</div>}
    {feed.length===0&&<div style={S.empty}>{photos.length===0?"업체를 등록하고 사진을 올려보세요":"해당 필터에 사진이 없어요"}</div>}
    {feed.length>0&&photoIdx<feed.length&&(()=>{const photo=feed[photoIdx];return<div style={{marginBottom:14}}><div style={{...S.card,padding:0,overflow:"hidden"}}><div style={{position:"relative",background:"#f5f5f0"}}><img src={photo.src} style={{width:"100%",maxHeight:520,objectFit:"contain",display:"block"}} alt=""/>{photoIdx>0&&<button onClick={()=>setPhotoIdx(photoIdx-1)} style={{position:"absolute",left:10,top:"50%",transform:"translateY(-50%)",background:"rgba(255,255,255,0.85)",border:"none",borderRadius:18,width:40,height:40,fontSize:18,cursor:"pointer"}}>◀</button>}{photoIdx<feed.length-1&&<button onClick={()=>setPhotoIdx(photoIdx+1)} style={{position:"absolute",right:10,top:"50%",transform:"translateY(-50%)",background:"rgba(255,255,255,0.85)",border:"none",borderRadius:18,width:40,height:40,fontSize:18,cursor:"pointer"}}>▶</button>}<div style={{position:"absolute",bottom:10,right:10,background:"rgba(0,0,0,0.45)",color:"#fff",padding:"3px 10px",borderRadius:10,fontSize:12}}>{photoIdx+1}/{feed.length}</div></div><div style={{padding:"14px 18px",display:"flex",justifyContent:"space-between",alignItems:"center"}}><div style={{display:"flex",alignItems:"center",gap:10}}><button onClick={()=>toggleLike(photo.id)} style={{background:"none",border:"none",fontSize:26,cursor:"pointer",padding:0}}>{photo.liked?"❤️":"🤍"}</button><span style={{padding:"4px 12px",borderRadius:10,fontSize:13,fontWeight:700,background:(SDM_T.find(t=>t.id===photo.vt)?.c||P.text)+"15",color:SDM_T.find(t=>t.id===photo.vt)?.c||P.text}}>{photo.vn}</span></div><button onClick={()=>rmPhoto(photo.id)} style={{background:"none",border:"none",color:P.textMuted,fontSize:15,cursor:"pointer"}}>🗑️</button></div></div><div style={{display:"flex",gap:5,overflowX:"auto",paddingTop:6}}>{feed.map((p,i)=><div key={p.id} onClick={()=>setPhotoIdx(i)} style={{width:56,height:56,borderRadius:9,overflow:"hidden",border:i===photoIdx?"3px solid "+P.periDk:"2px solid transparent",cursor:"pointer",flexShrink:0,position:"relative"}}><img src={p.src} style={{width:"100%",height:"100%",objectFit:"cover"}} alt=""/>{p.liked&&<div style={{position:"absolute",bottom:1,right:1,fontSize:10}}>❤️</div>}</div>)}</div></div>;})()}
  </div>;}

/* ═══ BUDGET ═══ */
function BudTab({data,setData}){const[show,setShow]=useState(false);const[editId,setEditId]=useState(null);const[f,setF]=useState({name:"",category:"venue",unitPrice:"",qty:"1",paid:""});const[ef,setEf]=useState({name:"",category:"venue",unitPrice:"",qty:"1",paid:""});const add=()=>{if(!f.name||!f.unitPrice)return;const u=parseInt(f.unitPrice)||0,q=parseInt(f.qty)||1;setData({...data,budget:[...data.budget,{id:Date.now().toString(),name:f.name,category:f.category,unitPrice:u,qty:q,amount:u*q,paid:parseInt(f.paid)||0}]});setF({name:"",category:"venue",unitPrice:"",qty:"1",paid:""});setShow(false);};const rm=id=>{if(confirm("정말 삭제하시겠습니까?"))setData({...data,budget:data.budget.filter(b=>b.id!==id)});};const openEd=item=>{setEditId(item.id);setEf({name:item.name,category:item.category,unitPrice:String(item.unitPrice),qty:String(item.qty),paid:String(item.paid)});};const saveEd=()=>{const u=parseInt(ef.unitPrice)||0,q=parseInt(ef.qty)||1;setData({...data,budget:data.budget.map(b=>b.id===editId?{...b,name:ef.name,category:ef.category,unitPrice:u,qty:q,amount:u*q,paid:parseInt(ef.paid)||0}:b)});setEditId(null);};const t=data.budget.reduce((s,b)=>s+b.amount,0),tp=data.budget.reduce((s,b)=>s+(b.paid||0),0);const dlB=()=>{dlCSV("예산",["카테고리","항목","단가","수량","견적","지출","잔여"],data.budget.map(b=>[(CAT[b.category]||CAT.etc).n,b.name,b.unitPrice,b.qty,b.amount,b.paid,b.amount-b.paid]));};const addAmt=(parseInt(f.unitPrice)||0)*(parseInt(f.qty)||1);const edAmt=(parseInt(ef.unitPrice)||0)*(parseInt(ef.qty)||1);
  const budF=(v,sv,amt)=><><div style={{marginBottom:18}}><label style={S.lbl}>항목명</label><input style={MI} value={v.name} onChange={e=>sv({...v,name:e.target.value})}/></div><div style={{marginBottom:18}}><label style={S.lbl}>카테고리</label><select style={MI} value={v.category} onChange={e=>sv({...v,category:e.target.value})}>{Object.entries(CAT).map(([k,c])=><option key={k} value={k}>{c.ic} {c.n}</option>)}</select></div><div style={{display:"flex",gap:10,marginBottom:18}}><div style={{flex:1}}><label style={S.lbl}>단가</label><input style={MI} type="number" value={v.unitPrice} onChange={e=>sv({...v,unitPrice:e.target.value})}/></div><div style={{width:24,display:"flex",alignItems:"flex-end",justifyContent:"center",paddingBottom:14,fontSize:18,color:P.textMuted}}>×</div><div style={{flex:1}}><label style={S.lbl}>수량</label><input style={MI} type="number" value={v.qty} onChange={e=>sv({...v,qty:e.target.value})}/></div></div><div style={{background:`linear-gradient(135deg,${P.blueBg},${P.lavBg})`,borderRadius:14,padding:"14px 18px",marginBottom:18,textAlign:"center"}}><div style={{fontSize:12,color:P.periDk,fontWeight:600}}>견적</div><div style={{fontSize:26,fontWeight:800,color:P.periDk}}>{fmtW(amt)}</div></div><div style={{marginBottom:18}}><label style={S.lbl}>지출액</label><input style={MI} type="number" value={v.paid} onChange={e=>sv({...v,paid:e.target.value})}/></div></>;
  return<div style={S.tab}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:20,flexWrap:"wrap",gap:8}}><h2 style={{...S.th,margin:0}}>🌻 예산</h2><DlB onClick={dlB}/></div>
    <div className="budget-summary" style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:12,marginBottom:20}}><div style={{...S.card,textAlign:"center",background:`linear-gradient(135deg,${P.blueBg},${P.blueLt})`,padding:"16px 12px"}}><div style={{fontSize:12,color:P.blueDk,fontWeight:700,marginBottom:6}}>총 예산</div><div className="budget-num" style={{fontSize:22,fontWeight:800,color:P.blueDk}}>{fmtW(t)}</div></div><div style={{...S.card,textAlign:"center",background:`linear-gradient(135deg,${P.lavBg},${P.lavLt})`,padding:"16px 12px"}}><div style={{fontSize:12,color:P.lavDk,fontWeight:700,marginBottom:6}}>지출</div><div className="budget-num" style={{fontSize:22,fontWeight:800,color:P.lavDk}}>{fmtW(tp)}</div></div><div style={{...S.card,textAlign:"center",background:`linear-gradient(135deg,${P.greenBg},${P.greenLt})`,padding:"16px 12px"}}><div style={{fontSize:12,color:P.greenDk,fontWeight:700,marginBottom:6}}>잔여</div><div className="budget-num" style={{fontSize:22,fontWeight:800,color:P.greenDk}}>{fmtW(t-tp)}</div></div></div>
    <button style={{...S.btn,width:"100%",marginBottom:20}} onClick={()=>{setF({name:"",category:"venue",unitPrice:"",qty:"1",paid:""});setShow(true);}}>+ 예산 추가</button>
    <Modal title="예산 추가" open={show} onClose={()=>setShow(false)}>{budF(f,setF,addAmt)}<button style={{...S.btn,width:"100%"}} onClick={add}>추가</button></Modal><Modal title="예산 수정" open={editId!==null} onClose={()=>setEditId(null)}>{budF(ef,setEf,edAmt)}<button style={{...S.btn,width:"100%"}} onClick={saveEd}>저장</button></Modal>
    {data.budget.length===0&&<div style={S.empty}>예산을 추가해보세요</div>}
    {data.budget.map(item=>{const pp=item.amount>0?Math.round(item.paid/item.amount*100):0;return<div key={item.id} style={{...S.card,marginBottom:10,padding:"16px 16px"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:8,flexWrap:"wrap",gap:4}}><div style={{display:"flex",alignItems:"center",gap:8,flexWrap:"wrap"}}><Bg cat={item.category}/><span style={{fontWeight:700,fontSize:15,color:P.text}}>{item.name}</span></div><div style={{display:"flex",gap:6}}><button style={S.ebtn} onClick={()=>openEd(item)}>수정</button><button style={S.dbtn} onClick={()=>rm(item.id)}>✕</button></div></div><div className="budget-detail" style={{fontSize:13,color:P.textSub,marginBottom:8,wordBreak:"break-all"}}>{fmtW(item.unitPrice)} × {item.qty} = <b style={{color:P.text}}>{fmtW(item.amount)}</b></div><div style={{height:8,background:P.greenBg,borderRadius:4,overflow:"hidden",marginBottom:8}}><div style={{height:"100%",background:`linear-gradient(90deg,${P.green},${P.blue})`,borderRadius:4,width:Math.min(pp,100)+"%"}}/></div><div className="budget-detail" style={{display:"flex",justifyContent:"space-between",fontSize:13,gap:8,flexWrap:"wrap"}}><span style={{color:P.lavDk}}>지출 {fmtW(item.paid)}</span><span style={{color:P.greenDk,fontWeight:700}}>잔여 {fmtW(item.amount-item.paid)}</span></div></div>;})}
  </div>;}

/* ═══ SCHEDULE — calendar uses dynamic checklist deadlines ═══ */
function ScheduleTab({data,setData}){const wd=data.weddingDate;const[year,setYear]=useState(()=>new Date().getFullYear());const[month,setMonth]=useState(()=>new Date().getMonth());const[show,setShow]=useState(false);const[editId,setEditId]=useState(null);const[f,setF]=useState({name:"",date:"",memo:""});const[ef,setEf]=useState({name:"",date:"",memo:""});const[selDay,setSelDay]=useState(null);
  const prev=()=>{if(month===0){setMonth(11);setYear(year-1);}else setMonth(month-1);setSelDay(null);};const next=()=>{if(month===11){setMonth(0);setYear(year+1);}else setMonth(month+1);setSelDay(null);};const goWedding=()=>{if(wd){const d=new Date(wd);setYear(d.getFullYear());setMonth(d.getMonth());setSelDay(null);}};
  const today=new Date();today.setHours(0,0,0,0);const fd=new Date(year,month,1).getDay();const dim=new Date(year,month+1,0).getDate();const days=[];for(let i=0;i<fd;i++)days.push(null);for(let i=1;i<=dim;i++)days.push(i);
  const events={};(data.keyDates||[]).forEach(d=>{const dt=new Date(d.date);if(dt.getFullYear()===year&&dt.getMonth()===month){const day=dt.getDate();if(!events[day])events[day]=[];events[day].push({name:d.name,color:P.periDk,id:d.id});}});
  // Dynamic checklist deadlines
  data.checklist.forEach(ph=>{const dl=phaseDeadlineDate(ph,wd);if(dl&&dl.getFullYear()===year&&dl.getMonth()===month){const day=dl.getDate();if(!events[day])events[day]=[];events[day].push({name:ph.emoji+" "+ph.label+" 마감",color:P.blueDk});}});
  if(wd){const wdd=new Date(wd);if(wdd.getFullYear()===year&&wdd.getMonth()===month){const day=wdd.getDate();if(!events[day])events[day]=[];events[day].unshift({name:"💍 결혼식",color:"#E91E63"});}}
  const fmtDt=(y,m,d)=>y+"-"+String(m+1).padStart(2,"0")+"-"+String(d).padStart(2,"0");
  const clickDay=(d)=>{if(!d)return;if(events[d]){setSelDay(d);}else{setF({name:"",date:fmtDt(year,month,d),memo:""});setShow(true);}};
  const addFromDay=()=>{setF({name:"",date:fmtDt(year,month,selDay),memo:""});setSelDay(null);setShow(true);};
  const add=()=>{if(!f.name||!f.date)return;setData({...data,keyDates:[...(data.keyDates||[]),{id:Date.now().toString(),...f}]});setF({name:"",date:"",memo:""});setShow(false);};const rm=id=>{if(confirm("정말 삭제하시겠습니까?"))setData({...data,keyDates:(data.keyDates||[]).filter(d=>d.id!==id)});};const openEd=d=>{setEditId(d.id);setEf({name:d.name,date:d.date,memo:d.memo||""});};const saveEd=()=>{setData({...data,keyDates:(data.keyDates||[]).map(d=>d.id===editId?{...d,...ef}:d)});setEditId(null);};const sorted=[...(data.keyDates||[])].sort((a,b)=>new Date(a.date)-new Date(b.date));const dlD=()=>{dlCSV("일정",["일정명","날짜","D-day","메모"],sorted.map(d=>[d.name,d.date,getDday(d.date),d.memo||""]));};
  const dtF=(v,sv)=><><div style={{marginBottom:18}}><label style={S.lbl}>일정명</label><input style={MI} placeholder="예: 상견례" value={v.name} onChange={e=>sv({...v,name:e.target.value})}/></div><div style={{marginBottom:18}}><label style={S.lbl}>날짜</label><input type="date" style={MI} value={v.date} onChange={e=>sv({...v,date:e.target.value})}/></div><div style={{marginBottom:18}}><label style={S.lbl}>메모</label><input style={MI} value={v.memo} onChange={e=>sv({...v,memo:e.target.value})}/></div></>;
  const selEvts=selDay?events[selDay]:null;
  return<div style={S.tab}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:20,flexWrap:"wrap",gap:8}}><h2 style={{...S.th,margin:0}}>📅 일정</h2><DlB onClick={dlD}/></div>
    <div style={{...S.card,marginBottom:18}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:16}}><button onClick={prev} style={S.calNav}>◀</button><div style={{display:"flex",alignItems:"center",gap:10}}><span style={{fontSize:18,fontWeight:700,color:P.periDk}}>{year}년 {month+1}월</span>{wd&&<button onClick={goWedding} style={{fontSize:11,padding:"4px 10px",background:P.lavLt,color:P.lavDk,border:"none",borderRadius:8,fontWeight:600,cursor:"pointer",fontFamily:FONT}}>💍</button>}</div><button onClick={next} style={S.calNav}>▶</button></div>
      <div className="cal-grid" style={{display:"grid",gridTemplateColumns:"repeat(7,1fr)",gap:3}}>{"일월화수목금토".split("").map((d,i)=><div key={d} style={{textAlign:"center",fontSize:12,fontWeight:700,color:i===0?"#E57373":i===6?P.blueDk:P.textSub,padding:"6px 0"}}>{d}</div>)}{days.map((d,i)=>{const ev=d?events[d]:null;const td=d&&today.getFullYear()===year&&today.getMonth()===month&&today.getDate()===d;const isSel=d&&d===selDay;return<div key={i} className="cal-cell" onClick={()=>clickDay(d)} style={{minHeight:56,padding:3,borderRadius:9,background:isSel?P.periDk+"20":td?P.periLt:ev?"#FAFCF8":"transparent",border:isSel?"2px solid "+P.periDk:td?"2px solid "+P.peri:"1px solid transparent",cursor:d?"pointer":"default"}}>{d&&<div style={{fontSize:12,fontWeight:td||isSel?700:500,color:td?P.periDk:i%7===0?"#E57373":P.text,textAlign:"center"}}>{d}</div>}{ev&&ev.slice(0,2).map((e,j)=><div key={j} className="cal-ev" style={{fontSize:9,fontWeight:600,color:"#fff",background:e.color,borderRadius:5,padding:"1px 3px",marginTop:2,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{e.name}</div>)}{ev&&<div className="cal-dot">{ev.slice(0,3).map((e,j)=><div key={j} style={{width:6,height:6,borderRadius:3,background:e.color}}/>)}</div>}</div>;})}</div>
      <p style={{fontSize:11,color:P.textMuted,margin:"10px 0 0",textAlign:"center"}}>날짜를 탭하면 일정 추가/확인</p>
    </div>
    {selDay&&selEvts&&<div style={{...S.card,marginBottom:18,border:"2px solid "+P.periLt}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:12}}><span style={{fontSize:16,fontWeight:700,color:P.periDk}}>{month+1}월 {selDay}일</span><button onClick={()=>setSelDay(null)} style={{background:P.periLt,border:"none",borderRadius:8,padding:"4px 10px",fontSize:12,color:P.periDk,cursor:"pointer",fontFamily:FONT}}>닫기</button></div>{selEvts.map((e,j)=><div key={j} style={{display:"flex",alignItems:"center",gap:8,padding:"8px 0",borderBottom:j<selEvts.length-1?"1px solid "+P.border+"60":"none"}}><div style={{width:8,height:8,borderRadius:4,background:e.color,flexShrink:0}}/><span style={{fontSize:14,color:P.text}}>{e.name}</span></div>)}<button style={{...S.btn,width:"100%",marginTop:12,padding:"10px 0",fontSize:13}} onClick={addFromDay}>+ 이 날짜에 일정 추가</button></div>}
    <button style={{...S.btn,width:"100%",marginBottom:18}} onClick={()=>{setF({name:"",date:"",memo:""});setShow(true);}}>+ 일정 추가</button>
    <Modal title="일정 추가" open={show} onClose={()=>setShow(false)}>{dtF(f,setF)}<button style={{...S.btn,width:"100%"}} onClick={add}>추가</button></Modal><Modal title="일정 수정" open={editId!==null} onClose={()=>setEditId(null)}>{dtF(ef,setEf)}<button style={{...S.btn,width:"100%"}} onClick={saveEd}>저장</button></Modal>
    {sorted.length===0&&<div style={S.empty}>일정을 추가해보세요</div>}
    {sorted.map(d=>{const dd=getDday(d.date);return<div key={d.id} style={{...S.card,marginBottom:10,opacity:new Date(d.date)<today?0.45:1,display:"flex",justifyContent:"space-between",alignItems:"center",padding:"14px 16px"}}><div style={{flex:1,cursor:"pointer"}} onClick={()=>openEd(d)}><div style={{fontSize:16,fontWeight:700,color:P.text}}>{d.name}</div><div style={{fontSize:14,color:P.periDk,marginTop:3}}>{fmtDate(d.date)} {dd>0?"(D-"+dd+")":dd===0?"(오늘!)":"(지남)"}</div>{d.memo&&<div style={{fontSize:13,color:P.textSub,marginTop:3}}>📝 {d.memo}</div>}</div><div style={{display:"flex",gap:6}}><button style={S.ebtn} onClick={()=>openEd(d)}>수정</button><button style={S.dbtn} onClick={()=>rm(d.id)}>✕</button></div></div>;})}
  </div>;}

/* ═══ CONTACTS ═══ */
function ContactsTab({data,setData}){const[show,setShow]=useState(false);const[editId,setEditId]=useState(null);const[f,setF]=useState({name:"",role:"",phone:"",memo:""});const[ef,setEf]=useState({name:"",role:"",phone:"",memo:""});const contacts=data.contacts||data.vendors||[];
  const add=()=>{if(!f.name)return;const nc=[...contacts,{id:Date.now().toString(),...f}];setData({...data,contacts:nc,vendors:nc});setF({name:"",role:"",phone:"",memo:""});setShow(false);};const rm=id=>{if(confirm("정말 삭제하시겠습니까?"))setData({...data,contacts:contacts.filter(v=>v.id!==id),vendors:contacts.filter(v=>v.id!==id)});};const openEd=v=>{setEditId(v.id);setEf({name:v.name,role:v.role||v.category||"",phone:v.phone||"",memo:v.memo||""});};const saveEd=()=>{const nc=contacts.map(v=>v.id===editId?{...v,...ef}:v);setData({...data,contacts:nc,vendors:nc});setEditId(null);};
  const cF=(v,sv)=><><div style={{marginBottom:18}}><label style={S.lbl}>이름 / 업체명</label><input style={MI} placeholder="예: 혜원 팀장님" value={v.name} onChange={e=>sv({...v,name:e.target.value})}/></div><div style={{marginBottom:18}}><label style={S.lbl}>역할</label><input style={MI} placeholder="예: 웨딩플래너" value={v.role} onChange={e=>sv({...v,role:e.target.value})}/></div><div style={{marginBottom:18}}><label style={S.lbl}>연락처</label><input style={MI} placeholder="010-0000-0000" value={v.phone} onChange={e=>sv({...v,phone:e.target.value})}/></div><div style={{marginBottom:18}}><label style={S.lbl}>메모</label><input style={MI} value={v.memo} onChange={e=>sv({...v,memo:e.target.value})}/></div></>;
  return<div style={S.tab}><h2 style={S.th}>📞 주요 연락처</h2><p style={{fontSize:13,color:P.textSub,margin:"-16px 0 18px"}}>소통해야 하는 주요 담당자를 저장하세요</p>
    <button style={{...S.btn,width:"100%",marginBottom:20}} onClick={()=>{setF({name:"",role:"",phone:"",memo:""});setShow(true);}}>+ 연락처 추가</button>
    <Modal title="연락처 추가" open={show} onClose={()=>setShow(false)}>{cF(f,setF)}<button style={{...S.btn,width:"100%"}} onClick={add}>추가</button></Modal><Modal title="연락처 수정" open={editId!==null} onClose={()=>setEditId(null)}>{cF(ef,setEf)}<button style={{...S.btn,width:"100%"}} onClick={saveEd}>저장</button></Modal>
    {contacts.length===0&&<div style={S.empty}>연락처를 추가해보세요</div>}
    <div className="vendor-grid" style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(260px,1fr))",gap:12}}>{contacts.map(v=><div key={v.id} className="contact-card" style={{...S.card,background:P.greenBg,padding:"16px 16px"}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:8}}>{(v.role||v.category)&&<span style={{padding:"3px 10px",borderRadius:8,fontSize:11,fontWeight:600,background:P.periLt,color:P.periDk}}>{v.role||(CAT[v.category]?.n)||""}</span>}<div style={{display:"flex",gap:5}}><button style={{...S.ebtn,padding:"4px 10px",fontSize:11}} onClick={e=>{e.stopPropagation();openEd(v);}}>수정</button><button style={S.dbtn} onClick={e=>{e.stopPropagation();rm(v.id);}}>✕</button></div></div><div style={{fontWeight:700,fontSize:16,color:P.text,marginBottom:6}}>{v.name}</div>{v.phone&&<a href={"tel:"+v.phone} onClick={e=>e.stopPropagation()} style={{display:"block",padding:"10px 14px",background:P.blueLt,borderRadius:10,fontSize:15,color:P.blueDk,textDecoration:"none",fontWeight:600,textAlign:"center",marginTop:4}}>📞 {v.phone}</a>}{v.memo&&<div style={{fontSize:13,color:P.textSub,marginTop:6}}>📝 {v.memo}</div>}</div>)}</div>
  </div>;}

/* ═══ SETTINGS ═══ */
function SetTab({data,setData,coupleKey,onLogout,onRefresh}){const[f,setF]=useState({groomName:data.groomName,brideName:data.brideName,weddingDate:data.weddingDate,weddingTime:data.weddingTime});const[saved,setSaved]=useState(false);const save=()=>{const m={};data.checklist.forEach(p=>p.items.forEach(i=>{m[i.id]={done:i.done,memo:i.memo||"",custom:i.custom,text:i.text,cat:i.cat,customCatName:i.customCatName,note:i.note};}));const nc=JSON.parse(JSON.stringify(CL_TEMPLATE)).map(p=>({...p,items:p.items.map(i=>({...i,done:m[i.id]?.done||false,memo:m[i.id]?.memo||""}))}));data.checklist.forEach((p,pi)=>{p.items.forEach(i=>{if(i.custom&&nc[pi])nc[pi].items.push(i);});});setData({...data,...f,checklist:nc});setSaved(true);setTimeout(()=>setSaved(false),2000);};
  return<div style={S.tab}><h2 style={S.th}>⚙️ 설정</h2><div style={S.card}><div style={{fontSize:14,color:P.textSub,marginBottom:20}}>커플 키: <b style={{color:P.periDk}}>{coupleKey}</b> · ☁️</div><div style={{display:"flex",flexDirection:"column",gap:14,maxWidth:420}}><div><label style={S.lbl}>신랑</label><input style={MI} value={f.groomName} onChange={e=>setF({...f,groomName:e.target.value})}/></div><div><label style={S.lbl}>신부</label><input style={MI} value={f.brideName} onChange={e=>setF({...f,brideName:e.target.value})}/></div><div><label style={S.lbl}>결혼 예정일</label><input type="date" style={MI} value={f.weddingDate} onChange={e=>setF({...f,weddingDate:e.target.value})}/><p style={{fontSize:11,color:P.textMuted,margin:"4px 0 0"}}>변경하면 체크리스트 기한이 준비기간 비율에 맞게 자동 재계산돼요</p></div><div><label style={S.lbl}>예식 시간</label><input type="time" style={MI} value={f.weddingTime} onChange={e=>setF({...f,weddingTime:e.target.value})}/></div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><button style={S.btn} onClick={save}>{saved?"✓ 저장!":"저장"}</button><button style={{padding:"12px 18px",background:P.blueLt,color:P.blueDk,border:"none",borderRadius:12,fontSize:14,fontWeight:600,cursor:"pointer",fontFamily:FONT}} onClick={onRefresh}>🔄 새로고침</button><button style={{padding:"12px 18px",background:"#F0F0F0",color:P.textSub,border:"none",borderRadius:12,fontSize:14,fontWeight:600,cursor:"pointer",fontFamily:FONT}} onClick={onLogout}>로그아웃</button></div></div></div></div>;}

/* ═══ AI CHATBOT — tab-aware floating assistant ═══ */
const CHAT_CTX={
  dashboard:{welcome:"결혼 준비 전반에 대해 궁금한 걸 물어보세요!",suggestions:["결혼 준비 어디서부터 시작해요?","플래너 필요한가요?","성수기 vs 비수기 차이는?","결혼 비용 평균이 얼마예요?"]},
  checklist:{welcome:"체크리스트에 대해 궁금한 걸 물어보세요!",suggestions:["지금 단계에서 가장 급한 건?","스드메 계약 시 주의할 점?","드레스투어 팁 알려주세요","촬영 준비물 뭐가 필요해요?"]},
  sdm:{welcome:"스드메 비교·선택에 대해 물어보세요!",suggestions:["스튜디오 선택 기준이 뭐예요?","드레스 투어 몇 곳이 적당해요?","메이크업 리허설 꼭 해야 해요?","야외스냅 vs 스튜디오 장단점?"]},
  budget:{welcome:"예산·견적에 대해 궁금한 걸 물어보세요!",suggestions:["스드메 평균 비용이 얼마예요?","웨딩홀 견적 볼 때 주의할 점?","숨은 비용 뭐가 있어요?","예산 절약 팁 알려주세요"]},
  schedule:{welcome:"일정 관리에 대해 물어보세요!",suggestions:["촬영 적정 시기가 언제예요?","청첩장 언제 보내야 해요?","상견례 준비 어떻게 해요?","식전 영상 언제까지 준비해요?"]},
  contacts:{welcome:"업체 소통에 대해 물어보세요!",suggestions:["업체에 첫 연락 어떻게 해요?","견적 요청 시 뭘 물어봐야 해요?","계약 전 확인할 사항은?","업체 변경은 가능한가요?"]},
  settings:{welcome:"앱 사용법에 대해 물어보세요!",suggestions:["커플 키 잊어버리면 어떡해요?","데이터 백업은 어떻게 돼요?","공유 링크는 어떻게 쓰나요?"]}
};

function ChatBot({tab,data}){
  const[open,setOpen]=useState(false);const[msgs,setMsgs]=useState([]);const[input,setInput]=useState("");const[loading,setLoading]=useState(false);const scrollRef=useRef(null);
  const ctx=CHAT_CTX[tab]||CHAT_CTX.dashboard;

  const buildSystem=()=>{let sys="당신은 친절하고 전문적인 웨딩 상담사입니다. 한국 결혼 준비에 대해 실용적인 조언을 해주세요.\n\n규칙:\n- 답변은 짧고 핵심적으로 (3~5문장)\n- 구체적인 숫자나 기간을 포함\n- 친근하지만 전문적인 톤\n- 모르는 건 솔직히 '전문가와 상담하세요'라고 안내";
    if(data?.weddingDate)sys+="\n\n이 커플의 정보:\n- 결혼 예정일: "+data.weddingDate+"\n- 신랑: "+(data.groomName||"미정")+", 신부: "+(data.brideName||"미정");
    if(tab==="checklist"&&data?.checklist){const cur=data.checklist.find(p=>phaseStatus(p,data.weddingDate)==="current");if(cur)sys+="\n- 현재 단계: "+cur.label+" ("+phaseLabel(cur,data.weddingDate)+")\n- 미완료 항목: "+cur.items.filter(i=>!i.done).map(i=>i.text).join(", ");}
    if(tab==="budget"&&data?.budget){const t=data.budget.reduce((s,b)=>s+b.amount,0),p=data.budget.reduce((s,b)=>s+(b.paid||0),0);sys+="\n- 총 예산: "+t.toLocaleString()+"원, 지출: "+p.toLocaleString()+"원\n- 등록 항목: "+data.budget.map(b=>b.name+"("+b.amount.toLocaleString()+"원)").join(", ");}
    if(tab==="sdm"){const v=(data?.sdmVendors||[]).map(v=>v.name+"("+({studio:"스튜디오",dress:"드레스",makeup:"메이크업"}[v.type]||"")+")").join(", ");if(v)sys+="\n- 등록된 스드메 업체: "+v;}
    return sys;};

  const send=async(text)=>{if(!text.trim()||loading)return;const userMsg={role:"user",content:text};const newMsgs=[...msgs,userMsg];setMsgs(newMsgs);setInput("");setLoading(true);
    try{const body=JSON.stringify({system:buildSystem(),messages:newMsgs.map(m=>({role:m.role,content:m.content}))});
      let res;try{res=await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body});if(!res.ok)throw new Error("serverless");}catch{res=await fetch("https://api.anthropic.com/v1/messages",{method:"POST",headers:{"Content-Type":"application/json","anthropic-version":"2023-06-01"},body});}
      if(res.ok){const d=await res.json();const reply=d.content?.map(c=>c.text||"").join("")||"답변을 생성하지 못했어요.";setMsgs([...newMsgs,{role:"assistant",content:reply}]);}else{setMsgs([...newMsgs,{role:"assistant",content:"죄송해요, 일시적인 오류가 발생했어요. 다시 질문해주세요!"}]);}
    }catch(e){console.error("Chat error:",e);setMsgs([...newMsgs,{role:"assistant",content:"네트워크 오류가 발생했어요. 다시 시도해주세요."}]);}setLoading(false);};

  useEffect(()=>{if(scrollRef.current)scrollRef.current.scrollTop=scrollRef.current.scrollHeight;},[msgs,loading]);
  useEffect(()=>{setMsgs([]);},[tab]);

  return<>
    {/* Floating button */}
    <button onClick={()=>setOpen(!open)} style={{position:"fixed",bottom:open?undefined:80,right:16,width:52,height:52,borderRadius:26,background:`linear-gradient(135deg,${P.peri},${P.blue})`,color:"#fff",border:"none",fontSize:24,cursor:"pointer",boxShadow:"0 4px 16px rgba(91,126,174,0.3)",zIndex:90,display:open?"none":"flex",alignItems:"center",justifyContent:"center"}}>💬</button>

    {/* Chat panel */}
    {open&&<div style={{position:"fixed",bottom:0,left:0,right:0,top:0,zIndex:95,display:"flex",flexDirection:"column",background:"rgba(40,50,70,0.3)",backdropFilter:"blur(4px)"}} onClick={()=>setOpen(false)}>
      <div style={{flex:1}} />
      <div onClick={e=>e.stopPropagation()} style={{background:"#fff",borderRadius:"20px 20px 0 0",maxHeight:"75vh",display:"flex",flexDirection:"column",boxShadow:"0 -8px 32px rgba(60,80,120,0.12)"}}>
        {/* Header */}
        <div style={{padding:"16px 20px",borderBottom:"1px solid "+P.border,display:"flex",justifyContent:"space-between",alignItems:"center",flexShrink:0}}>
          <div><div style={{fontSize:16,fontWeight:700,color:P.periDk}}>🤖 AI 웨딩 상담</div><div style={{fontSize:12,color:P.textMuted,marginTop:2}}>{ctx.welcome}</div></div>
          <button onClick={()=>setOpen(false)} style={{background:P.periLt,border:"none",width:34,height:34,borderRadius:10,fontSize:15,color:P.periDk,cursor:"pointer"}}>✕</button>
        </div>

        {/* Messages */}
        <div ref={scrollRef} style={{flex:1,overflowY:"auto",padding:"16px 20px",minHeight:200,maxHeight:"50vh"}}>
          {msgs.length===0&&<div style={{display:"flex",flexDirection:"column",gap:8}}>{ctx.suggestions.map((q,i)=><button key={i} onClick={()=>send(q)} style={{padding:"10px 14px",background:P.greenBg,border:"1px solid "+P.border,borderRadius:12,fontSize:13,color:P.text,cursor:"pointer",fontFamily:FONT,textAlign:"left"}}>{q}</button>)}</div>}
          {msgs.map((m,i)=><div key={i} style={{display:"flex",justifyContent:m.role==="user"?"flex-end":"flex-start",marginBottom:10}}>
            <div style={{maxWidth:"85%",padding:"10px 14px",borderRadius:m.role==="user"?"14px 14px 4px 14px":"14px 14px 14px 4px",background:m.role==="user"?`linear-gradient(135deg,${P.peri},${P.blue})`:P.greenBg,color:m.role==="user"?"#fff":P.text,fontSize:14,lineHeight:1.7,whiteSpace:"pre-wrap"}}>{m.content}</div>
          </div>)}
          {loading&&<div style={{display:"flex",justifyContent:"flex-start",marginBottom:10}}><div style={{padding:"10px 14px",borderRadius:"14px 14px 14px 4px",background:P.greenBg,fontSize:14,color:P.textMuted}}>답변 작성 중...</div></div>}
        </div>

        {/* Input */}
        <div style={{padding:"12px 16px",borderTop:"1px solid "+P.border,display:"flex",gap:8,flexShrink:0}}>
          <input style={{...MI,flex:1,fontSize:14,padding:"10px 14px"}} placeholder="궁금한 걸 물어보세요..." value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send(input);}}}/>
          <button onClick={()=>send(input)} disabled={loading||!input.trim()} style={{padding:"10px 18px",background:loading||!input.trim()?"#E0E0E0":`linear-gradient(135deg,${P.peri},${P.blue})`,color:loading||!input.trim()?P.textMuted:"#fff",border:"none",borderRadius:11,fontSize:14,fontWeight:700,cursor:loading?"default":"pointer",fontFamily:FONT,flexShrink:0}}>전송</button>
        </div>
      </div>
    </div>}
  </>;
}

/* ═══ MAIN ═══ */
const TABS=[{id:"dashboard",l:"홈",i:"🏡"},{id:"checklist",l:"체크리스트",i:"🌿"},{id:"sdm",l:"스드메",i:"💐"},{id:"budget",l:"예산",i:"🌻"},{id:"schedule",l:"일정",i:"📅"},{id:"contacts",l:"연락처",i:"📞"},{id:"settings",l:"설정",i:"⚙️"}];

export default function App(){const[ck,setCk]=useState(null);const[data,setDR]=useState(null);const[tab,setTab]=useState("dashboard");const[loading,setLoading]=useState(true);const[toast,setToast]=useState({msg:"",show:false});const[shareMode,setShareMode]=useState(false);const timerRef=useRef(null);const showT=msg=>{setToast({msg,show:true});setTimeout(()=>setToast({msg:"",show:false}),2000);};
  useEffect(()=>{const params=new URLSearchParams(window.location.search);const shareKey=params.get("share");if(shareKey){setShareMode(true);dbLoad(shareKey).then(d=>{if(d)setDR(migrateData(d));setLoading(false);});return;}const k=localStorage.getItem("wp_ck");if(k){dbLoad(k).then(d=>{if(d){setCk(k);setDR(migrateData(d));}setLoading(false);});}else setLoading(false);},[]);
  const onLogin=(key,d)=>{setCk(key);setDR(migrateData(d));localStorage.setItem("wp_ck",key);};const onLogout=()=>{localStorage.removeItem("wp_ck");setCk(null);setDR(null);setTab("dashboard");};const onRefresh=async()=>{if(!ck)return;setLoading(true);const d=await dbLoad(ck);if(d){setDR(migrateData(d));showT("최신 데이터 불러옴");}setLoading(false);};
  const setData=useCallback(nd=>{setDR(nd);try{localStorage.setItem("wp_bk_"+(ck||""),JSON.stringify(nd));}catch{}if(timerRef.current)clearTimeout(timerRef.current);timerRef.current=setTimeout(()=>{if(ck)dbSave(ck,nd).then(()=>showT("☁️ 저장 완료"));},600);},[ck]);

  if(loading)return<div style={{minHeight:"100vh",display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",fontFamily:FONT,background:P.bg}}><div style={{fontSize:44}}>💍</div><div style={{color:P.peri,marginTop:10,fontSize:14}}>불러오는 중...</div></div>;
  if(shareMode&&data)return<ShareView data={data}/>;
  if(!ck||!data)return<><LoginScreen onLogin={onLogin}/><Toast {...toast}/></>;
  if(!data.isSetup)return<><SetupScreen data={data} setData={setData} onBack={onLogout}/><Toast {...toast}/></>;

  return<><div style={S.app}>
    <nav style={S.side}><div style={{display:"flex",alignItems:"center",gap:7,padding:"0 10px 8px"}}><span style={{fontSize:20}}>💍</span><span style={{fontSize:16,fontWeight:700,color:P.periDk}}>Wedding</span></div><div style={{fontSize:12,color:P.textSub,padding:"0 12px 12px",borderBottom:"1px solid "+P.border,marginBottom:8}}>{data.groomName} ♥ {data.brideName}</div>{TABS.map(t=><button key={t.id} style={{display:"flex",alignItems:"center",gap:9,padding:"10px 12px",border:"none",borderRadius:11,fontSize:14,cursor:"pointer",fontFamily:FONT,background:tab===t.id?P.periLt:"transparent",color:tab===t.id?P.periDk:P.textSub,fontWeight:tab===t.id?700:400}} onClick={()=>setTab(t.id)}><span>{t.i}</span><span>{t.l}</span></button>)}</nav>
    <nav style={S.mob}>{TABS.map(t=><button key={t.id} style={{display:"flex",flexDirection:"column",alignItems:"center",gap:1,background:"none",border:"none",padding:"6px 0",cursor:"pointer",fontFamily:FONT,color:tab===t.id?P.periDk:P.textMuted,fontWeight:tab===t.id?700:400,minWidth:0,flex:1}} onClick={()=>setTab(t.id)}><span style={{fontSize:20}}>{t.i}</span>{tab===t.id&&<span style={{fontSize:9,lineHeight:1}}>{t.l}</span>}</button>)}</nav>
    <main style={S.main}>
      {tab==="dashboard"&&<Dash data={data} setTab={setTab}/>}
      {tab==="checklist"&&<CLTab data={data} setData={setData}/>}
      {tab==="sdm"&&<SdmTab data={data} setData={setData} coupleKey={ck} showT={showT}/>}
      {tab==="budget"&&<BudTab data={data} setData={setData}/>}
      {tab==="schedule"&&<ScheduleTab data={data} setData={setData}/>}
      {tab==="contacts"&&<ContactsTab data={data} setData={setData}/>}
      {tab==="settings"&&<SetTab data={data} setData={setData} coupleKey={ck} onLogout={onLogout} onRefresh={onRefresh}/>}
    </main>
  </div><ChatBot tab={tab} data={data}/><Toast {...toast}/></>;
}

const S={wrap:{minHeight:"100vh",display:"flex",alignItems:"center",justifyContent:"center",background:`linear-gradient(150deg,${P.greenBg} 0%,${P.blueBg} 30%,${P.periBg} 60%,${P.lavBg} 100%)`,padding:12,fontFamily:FONT,position:"relative",overflow:"hidden"},lc:{background:"rgba(255,255,255,0.92)",borderRadius:24,padding:"36px 30px",maxWidth:400,width:"100%",boxShadow:"0 20px 56px rgba(91,126,174,0.08)",textAlign:"center",backdropFilter:"blur(12px)",position:"relative",zIndex:2},lbl:{fontSize:13,fontWeight:600,color:"#4A4A5A",display:"block",marginBottom:5},btn:{padding:"13px 24px",background:`linear-gradient(135deg,${P.peri},${P.blue})`,color:"#fff",border:"none",borderRadius:12,fontSize:15,fontWeight:700,cursor:"pointer",fontFamily:FONT,boxShadow:"0 4px 12px rgba(110,200,228,0.2)"},app:{display:"flex",minHeight:"100vh",background:P.bg,fontFamily:FONT},side:{width:200,background:"rgba(246,249,242,0.98)",borderRight:"1px solid "+P.border,padding:"20px 10px",display:"flex",flexDirection:"column",gap:2,position:"fixed",top:0,left:0,bottom:0,zIndex:10,overflowY:"auto"},mob:{display:"none",position:"fixed",bottom:0,left:0,right:0,background:"rgba(246,249,242,0.98)",borderTop:"1px solid "+P.border,zIndex:10,justifyContent:"space-around",padding:"4px 0 env(safe-area-inset-bottom,4px)"},main:{flex:1,marginLeft:200,padding:"24px 36px 80px",minHeight:"100vh",overflowY:"auto"},dday:{background:`linear-gradient(135deg,${P.greenBg} 0%,${P.blueBg} 30%,${P.periBg} 60%,${P.lavBg} 100%)`,borderRadius:24,padding:"44px 28px",textAlign:"center",border:"1px solid "+P.border,position:"relative",overflow:"hidden"},card:{background:"#fff",borderRadius:18,padding:"20px 20px",border:"1px solid "+P.border,boxShadow:"0 2px 8px rgba(91,126,174,0.03)"},lnk:{background:"none",border:"none",color:P.periDk,fontSize:13,fontWeight:700,cursor:"pointer",fontFamily:FONT,padding:0},tab:{},th:{fontSize:24,fontWeight:700,color:P.periDk,margin:"0 0 20px"},ebtn:{background:P.periLt,border:"none",borderRadius:9,padding:"7px 14px",fontSize:13,fontWeight:600,color:P.periDk,cursor:"pointer",fontFamily:FONT},dbtn:{background:"none",border:"none",color:P.textMuted,fontSize:17,cursor:"pointer",padding:"2px 6px"},empty:{textAlign:"center",padding:"44px 16px",color:P.textMuted,fontSize:14,gridColumn:"1 / -1"},calNav:{background:P.periLt,border:"none",borderRadius:10,width:40,height:40,fontSize:15,color:P.periDk,cursor:"pointer",display:"flex",alignItems:"center",justifyContent:"center",fontWeight:700}};
const fl=document.createElement("link");fl.rel="stylesheet";fl.href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/static/pretendard.min.css";document.head.appendChild(fl);
const pp=document.createElement("script");pp.src="https://cdn.jsdelivr.net/npm/pptxgenjs@3.12.0/dist/pptxgen.bundle.js";document.head.appendChild(pp);
const se=document.createElement("style");se.textContent=`@media(max-width:768px){nav[style*="width: 200"]{display:none !important;}nav[style*="display: none"]{display:flex !important;}main[style*="margin-left: 200"]{margin-left:0 !important;padding:14px 14px 90px !important;}.dday-num{font-size:48px !important;}.couple-name{font-size:17px !important;}.couple-row{gap:16px !important;}.stat-grid,.budget-summary{grid-template-columns:1fr !important;}.budget-main{font-size:20px !important;}.budget-num{font-size:20px !important;}.vendor-grid{grid-template-columns:1fr !important;}.modal-inner{padding:22px 16px !important;margin:6px;border-radius:18px !important;}.cal-cell{min-height:40px !important;}.cal-cell .cal-ev{display:none !important;}.cal-cell .cal-dot{display:flex !important;}.sdm-vendor-btns{flex-wrap:wrap !important;gap:6px !important;}.cl-item-wrap{flex-direction:column !important;align-items:flex-start !important;gap:6px !important;}.budget-detail{flex-wrap:wrap !important;}.contact-card{cursor:pointer;}}input:focus,select:focus,textarea:focus{border-color:${P.peri} !important;box-shadow:0 0 0 3px rgba(146,173,216,0.15) !important;}button:hover{opacity:0.88;}*{-webkit-font-smoothing:antialiased;box-sizing:border-box;-webkit-tap-highlight-color:transparent;}.cal-dot{display:none;gap:3px;justify-content:center;margin-top:2px;}`;document.head.appendChild(se);
